config/routes.rb
Rails.application.routes.draw do
  resources :detail_quotation_products
  # ROOT PATH
  authenticate :user, lambda { |u| u.administrator? } do
    apipie
  end
  root 'home#index'
  # resources
  devise_for :users, :controllers => {:sessions => 'users/sessions'}
  get '/users/search', to: 'users#search'
  resources :users
  get '/choose_role', to: 'users#choose_role', as: 'choose_role'
  get '/change_role', to: 'users#change_role', as: 'change_role'
  post '/set_role', to: 'users#set_role', as: 'set_role'
  
  resources :promotional_codes
  resources :banners

  # DASHBOARD
  get '/home/filter', to: 'home#filter', as: 'filter_home'
  # BANNERS
  get '/banner/reference', to: 'banners#reference_banner', as: 'reference_banner'
  # PRODUCTOS
  get '/business_units', to: 'products#business_units', as: 'business_units'
  get  '/:business_unit/products', to: 'products#index'     , as: 'products' 
  get  '/search', to: 'products#search', as: 'search_products'
  get  '/product/:sku', to: 'products#show', as: 'product'
  get  '/product/bstock/:sku', to: 'products#show', bstock: true, as: 'bstock_product'
  patch '/product/:id', to: 'products#update', as: 'update_product'
  get '/cart/:id/mandatories_by_instalation/:instalation_id', to: 'cart#mandatories_by_instalation', as: 'mandatories_by_instalation'
  get '/bstocks', to: 'products#bstock', as: 'bstocks'
  post '/product/destroy', to: 'products#destroy', as: 'delete_product'
  patch '/product/:sku/syncronize_with_miele_core', to: 'products#synchronize_one_product_with_miele_core', as: 'synchronize_one_product_with_miele_core'
  
  # COTIZACIONES
  get 'quotations/:id/resumen'     , to: 'quotations#resumen' , as: 'quotation_resumen'
  get '/quotations/search'         , to: 'quotations#search', as: 'search_quotations'
  post '/quotations/:id/check_dispatch/:commune', to: 'quotations#check_dispatch', as: 'check_dispatch'
  post '/quotation/:id/update_payment_info', to: 'quotations#update_payment_info', as: 'update_payment_info'
  get '/quotations/:id/pay_debt', to: 'quotations#pay_debt', as: 'pay_debt'
  post '/quotation/:id/reactivate', to: 'quotations#reactivate', as: 'reactivate_quotation'
  post '/quotation/:id/reactivate_for_project', to: 'quotations#reactivate_for_project', as: 'reactivate_for_project'
  post '/quotation/:id/update_quotation', to: 'quotations#update_quotation', as: 'update_custom_quotation'
  post '/quotation/get_dispatch_cost', to: 'quotations#get_dispatch_cost'
  post '/quotation/get_dispatch_cost_show', to: 'quotations#get_dispatch_cost_show'
  post '/quotation/set_dispatch_value', to: 'quotations#set_dispatch_value'
  post '/quotation/set_installation_value', to: 'quotations#set_installation_value'
  patch '/quotation/:id/update_total_from_view', to: 'quotations#update_total_from_view'


  #normal flow
  post '/quotation/:id/finish', to: 'quotation_flow#cancel_quotation', as: 'cancel_quotation'
  post '/quotation/:id/activate', to: 'quotation_flow#activate', as: 'activate_quotation'
  post '/quotation/:id/dispatch', to: 'quotation_flow#dispatch_activation', as: 'dispatch_quotation'
  post '/quotation/:id/dispatch_confirm', to: 'quotation_flow#dispatch_confirm', as: 'dispatch_confirm_quotation'
  post '/quotation/:id/instalation', to: 'quotation_flow#instalation', as: 'instalation_quotation'
  post '/quotation/:id/activate_home_program', to: 'quotation_flow#activate_home_program', as: 'activate_home_program_quotation'
  post '/quotation/:id/load_billing_documents', to: 'quotation_flow#load_billing_documents', as: 'load_billing_documents'
  #project flow
  post '/quotation/:id/negotiation_quotation', to: 'quotation_flow#negotiation_quotation', as: 'negotiation_quotation'
  post '/quotation/:id/close_quotation', to: 'quotation_flow#close_quotation', as: 'close_quotation'
  post '/quotation/:id/lead_quotation', to: 'quotation_flow#lead_quotation', as: 'lead_quotation'
  #retail flow
  post '/quotation/:id/activate_retail', to: 'quotation_retail#activate_retail', as: 'activate_retail'
  post '/quotation/:id/activate_finance_retail', to: 'quotation_retail#activate_finance_retail', as: 'activate_finance_retail'
  post '/quotation/:id/update_quantities', to: 'quotation_retail#update_quantities', as: 'update_quantities'
  post 'quotations/:id/new_version', to: 'quotations#new_version', as: :new_version
  delete 'quotations/:id', to: 'quotations#destroy', as: :delete_version
  get 'quotations/checkout', to: 'quotations#checkout'
  post 'quotations/checkout_instalation', to: 'quotations#checkout_instalation', as: 'checkout_instalation'
  get 'quotations/:id/send_dispatch_configuration_alert', to: 'quotations#send_dispatch_configuration_alert', as: :send_dispatch_configuration_alert
  patch '/set_instalation_check', to: 'quotations#set_instalation_check'
  get 'quotations/:id/unit_real_states', to: 'quotations#get_unit_real_states'


  resources :quotations, only: [:index, :new, :create, :show, :update, :edit]
  # CARRITO
  get  '/cart', to: 'cart#index', as: 'cart'
  post  '/cart/from_quotation', to: 'cart#from_quotation', as: 'cart_from_quotation'
  post '/cart/add_mandatory_to_cart', to: 'cart#add_mandatory_to_cart', as: 'add_mandatory_to_cart'
  post '/cart/apply_discount', to: 'cart#apply_discount', as: 'apply_discount'
  post 'add_product/:id'           , to: 'cart#add_product'   , as: 'add_product_to_cart'
  post '/add_product_bstock/:id', to: 'cart#add_product_bstock', as: 'add_product_bstock'
  post 'minus_product/:id'         , to: 'cart#minus_product' , as: 'minus_product_to_cart'
  post 'plus_product/:id'          , to: 'cart#plus_product'  , as: 'plus_product_to_cart'
  delete '/cart/empty'               , to: 'cart#empty'         , as: 'empty_cart'
  delete '/remove_product/:id'     , to: 'cart#remove_product', as: 'remove_product'
  post '/change_payment/:percent'  , to: 'cart#change_percent', as: 'change_percent'
  post '/apply_promotion/:type/:id'      , to: 'cart#apply_promotion', as: 'apply_promotion'
  post '/set_dispatch/:id/:value', to: 'cart#set_dispatch', as: 'set_dispatch'
  post '/set_instalation/:id', to: 'cart#set_instalation', as: 'set_instalation'
  get 'cart/update_totals'
  post 'cart/update_item_price'
  post 'cart_items/calculate_margen', to: "cart#calculate_margen"

  #carga de datos
  get '/data_upload'               , to: 'data_upload#upload_info', as: 'upload_info'
  post '/upload/product_photos'    , to: 'data_upload#load_photos', as: 'upload_product_photos'
  post '/upload/mandatory_products', to: 'data_upload#load_mandatory', as: 'upload_mandatory'
  post '/upload/products'          , to: 'data_upload#load_products', as: 'upload_products'
  post '/upload/discounts', to: 'data_upload#load_discounts', as: 'upload_discounts'
  post '/upload/addressees', to: 'data_upload#load_addressees', as: 'upload_addressees'
  post '/upload/stock', to: 'data_upload#load_stock', as: 'upload_stock'
  post '/upload/technical_images', to: 'data_upload#load_technical_images', as: 'upload_technical_images'
  post '/upload/load_comparator_info', to: 'data_upload#load_comparator_info', as: 'load_comparator_info'
  post '/upload/load_homologate_tnr', to: 'data_upload#load_homologate_tnr', as: 'load_homologate_tnr'
  post 'upload/load_oc_retail', to: 'data_upload#load_oc_retail', as: 'load_oc_retail'
  post 'upload/load_quotation_project', to: 'data_upload#load_quotation_project', as: 'load_quotation_project'
  post 'upload/load_cost_center', to: 'data_upload#load_cost_center', as: 'load_cost_center'
  post '/upload/load_miele_roles', to: 'data_upload#load_miele_roles', as: 'load_miele_roles'
  post '/upload/commission_levels', to: 'data_upload#load_commission_levels', as: 'load_commission_levels'
  post '/upload/load_project_installation_value', to: 'data_upload#load_project_installation_value', as: 'load_project_installation_value'
  post '/upload/load_project_installation_discount', to: 'data_upload#load_project_installation_discount', as: 'load_project_installation_discount'
  post '/upload/load_dispatch_rule', to: 'data_upload#load_dispatch_rule', as: 'load_dispatch_rule'
  post '/upload/save_margen', to: 'data_upload#load_save_margen', as: 'load_save_margen'


  patch '/update/customer_core_ids', to: 'data_upload#update_customer_core_ids', as: 'update_customer_core_ids'
  patch '/update/product_core_ids', to: 'data_upload#update_product_core_ids', as: 'update_product_core_ids'
  patch '/update/synchronizeProductsWithMieleCore', to: 'data_upload#synchronizeProductsWithMieleCore', as: 'synchronize_products_with_miele_core'

  get '/download/stock', to: 'data_upload#download_stock', as: 'download_stock'
  get '/download/products_template', to: 'data_upload#download_products', as: 'download_products'
  get '/download/discounts', to: 'data_upload#download_discounts', as: 'download_discounts'
  get '/download/addressees', to: 'data_upload#download_addressees', as: 'download_addressees'
  get '/download/commissions_table', to: 'data_upload#download_commissions_table', as: 'download_commissions_table'
  get '/download/cost_center', to: 'data_upload#download_cost_center', as: 'download_cost_center'
  get '/download/miele_roles', to: 'data_upload#download_miele_roles', as: 'download_miele_roles'
  get '/download/tnr_homologated', to: 'data_upload#download_tnr_homologated', as: 'download_tnr_homologated'
  #usuarios
  get '/upload_users', to: 'users#upload_users', as: 'upload_users'
  post '/load_users', to: 'users#load_users', as: 'load_users'
  post '/users/create_user' => 'users#create_user'
  post '/user/toggle/:id', to: 'users#toggle', as: 'toggle_user'
  get '/download/users', to: 'users#download_users', as: 'download_users'
  #clientes
  get '/customers/search', to: 'customers#search', as: 'search_customer'
  get '/clientes', to: 'customers#search_tracking', as: 'search_tracking'
  get '/busqueda', to: 'customers#find_by_rut_and_code', as: 'find_by_rut_and_code'
  #templates

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
	after_action :empty_comparator, only: [:create]
	skip_before_action :check_role, only: :destroy
	private 

	def empty_comparator
		if comparator = Comparator.find_by(user: resource)
			comparator.comparator_products.destroy_all
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	before_action :set_user, only: [:toggle, :edit, :destroy]
	before_action :set_paper_trail_whodunnit, only: [:toggle]
	load_and_authorize_resource

	def index
		if current_user.manager?
			@users = current_user.sale_channel.users.order('id DESC').paginate(page: params[:page], per_page: 10)
			@items = current_user.sale_channel.users.size
		elsif current_user.administrator? or current_user.is_finance_manager?
			@users = User.all.order('id DESC').paginate(page: params[:page], per_page: 10)
			@items = User.all.size
		elsif current_user.is_finance?
			@users = User.joins(:role).where('roles.name = ? OR roles.name = ?','Manager Finanzas','Finanzas').paginate(page: params[:page], per_page: 10)
			@items = User.joins(:role).where('roles.name = ? OR roles.name = ?','Manager Finanzas','Finanzas').size
		elsif current_user.is_manager_instalation?
			@users = User.joins(:role).where('roles.name = ? OR roles.name = ?','Manager Instalación','Instalación').paginate(page: params[:page], per_page: 10)
			@items = User.joins(:role).where('roles.name = ? OR roles.name = ?','Manager Instalación','Instalación').size
		elsif current_user.is_manager_dispatch?
			@users = User.joins(:role).where('roles.name = ? OR roles.name = ?','Manager Despacho','Despacho').paginate(page: params[:page], per_page: 10)
			@items = User.joins(:role).where('roles.name = ? OR roles.name = ?','Manager Despacho','Despacho').size
		end
	end

	def new
		@user = User.new
		set_dropdowns
		@roles = @roles.pluck(:name, :id)
	end

	def edit
		set_dropdowns
		roles = @roles.pluck(:name, :id)
		user_roles = current_user.custom_roles.map{|r| [r.role.name, r.role.id]}
		@roles = roles | user_roles
	end

	def destroy
		respond_to do |format|
			if @user.destroy
				format.html{redirect_to users_path, notice: 'Usuario eliminado con éxito.'}
			else
				format.html{redirect_to users_path, alert: 'Error: '+@user.errors.full_messages.join(',')}
			end
		end
	end

	def update
		respond_to do |format|
			if @user.update(user_params)
				@user.update(@user.custom_roles.first.attributes.except("id","user_id", "created_at", "updated_at"))
				format.html{redirect_to users_path, notice: 'Usuario actualizado con éxito.'}
			else
				format.html{redirect_to edit_user_path(@user), alert: 'Error: '+@user.errors.full_messages.join(',')}
			end
		end
	end

	def create_user
		params[:user][:password] = User.default_pass
		params[:user][:active] = false if current_user.cant_create
		user = User.new(user_params)
		respond_to do |format|
			if user.save
				user.update(user.custom_roles.first.attributes.except("id","user_id", "created_at", "updated_at"))
				UserMailer.welcome_mail(user).deliver_later
				format.html{redirect_to users_path, notice: 'Usuario creado con éxito.'}
			else
				format.html{redirect_to new_user_path, alert: 'Error: '+user.errors.full_messages.join(',')}
			end
		end
	end

	def upload_users
		
	end

	def load_users
		success, session[:errors] = User.load_from_excel(params[:file])
		respond_to do |format|
			if success and session[:errors].empty?
				format.html{redirect_to request.env["HTTP_REFERER"], notice: 'Usuarios cargados con éxito.'}
			else
				format.html{redirect_to request.env["HTTP_REFERER"], alert: 'Ha ocurrido un problema al cargar los usuarios.'}
			end
		end 
	end

	def download_users
		@users = User.all.order(lastname: :asc)
		respond_to do |format|
			format.xlsx{render xlsx: 'download_users', filename: "plantilla_usuarios_#{Date.today.strftime("%d/%m/%Y")}.xlsx"}
		end
	end

	def toggle
		respond_to do |format|
			if @user.toggle!(:active)
				format.js{ (@success = true).to_json }
			else
				format.js{ (@success = false).to_json }
			end
		end
	end

	def template
		send_file(
			"#{Rails.root}/public/resources/plantilla_usuarios.xlsx",
			filename: "plantilla_usuarios.xlsx",
			type: "application/xlsx"
			)
	end

	def change_role
		session[:can_navigate] = false
		redirect_to choose_role_path
	end

	def choose_role
		redirect_to root_path if session[:can_navigate]
		@roles = current_user.custom_roles
	end

	def set_role
		custom_r = CustomRole.find_by(id: params[:custom_role_id])
		current_user.update(custom_r.attributes.except("id","user_id", "created_at", "updated_at"))
		session[:can_navigate] = true
		redirect_to root_path
	end

	def search
		@users = User.where(
		"
		  translate(LOWER(name),'áâãäåāăąÁÂÃÄÅĀĂĄèééêëēĕėęěĒĔĖĘĚìíîïìĩīĭÌÍÎÏÌĨĪĬóôõöōŏőÒÓÔÕÖŌŎŐùúûüũūŭůÙÚÛÜŨŪŬŮñÑ','aaaaaaaaaaaaaaaaeeeeeeeeeeeeeeeiiiiiiiiiiiiiiiiooooooooooooooouuuuuuuuuuuuuuuunN') ilike ? or
		  translate(LOWER(lastname),'áâãäåāăąÁÂÃÄÅĀĂĄèééêëēĕėęěĒĔĖĘĚìíîïìĩīĭÌÍÎÏÌĨĪĬóôõöōŏőÒÓÔÕÖŌŎŐùúûüũūŭůÙÚÛÜŨŪŬŮñÑ','aaaaaaaaaaaaaaaaeeeeeeeeeeeeeeeiiiiiiiiiiiiiiiiooooooooooooooouuuuuuuuuuuuuuuunN') ilike ? or
		  translate(LOWER(second_lastname),'áâãäåāăąÁÂÃÄÅĀĂĄèééêëēĕėęěĒĔĖĘĚìíîïìĩīĭÌÍÎÏÌĨĪĬóôõöōŏőÒÓÔÕÖŌŎŐùúûüũūŭůÙÚÛÜŨŪŬŮñÑ','aaaaaaaaaaaaaaaaeeeeeeeeeeeeeeeiiiiiiiiiiiiiiiiooooooooooooooouuuuuuuuuuuuuuuunN') ilike ? or
			email ilike ?
		",
			'%'+ActiveSupport::Inflector.transliterate(params[:search_user]).downcase+'%', '%'+ActiveSupport::Inflector.transliterate(params[:search_user]).downcase+'%',
			'%'+ActiveSupport::Inflector.transliterate(params[:search_user]).downcase+'%', '%'+ActiveSupport::Inflector.transliterate(params[:search_user]).downcase+'%'
		)
	
		@items = @users.size
		respond_to do |format|
			format.html do 
				@users = @users.paginate(page: params[:page], per_page: 10)
				render 'index'
			end
			format.json 
		end
	end	

	private

	def set_dropdowns
		if current_user.manager?
			@roles = Role.where(name: ["Manager","Seller"])
			@sale_channels = SaleChannel.where(name: current_user.sale_channel.name)
		elsif current_user.administrator? or current_user.is_finance_manager?
			@roles = Role.all
			@sale_channels = SaleChannel.all
		elsif current_user.is_finance?
			@roles = Role.where(name: ["Finanzas","Manager Finanzas"])
		elsif current_user.is_manager_instalation?
			@roles = Role.where(name: ["Instalación","Manager Instalación"])
		elsif current_user.is_manager_dispatch?
			@roles = Role.where(name: ["Despacho","Manager Despacho"])
		end
	end

	def set_user
		@user = User.find_by(id: params[:id])
	end

	def user_params
		params.require(:user).permit(
			:role_id,
			:name, 
			:lastname, 
			:second_lastname,
			:email, 
			:phone, 
			:cost_center_id,
			:shop,
			:workday,
			:password,
			:sale_channel_id,
			:miele_role_id,
			:active,
			custom_roles_attributes: [:role_id, :sale_channel_id, :cost_center_id, :id, :_destroy]
			)
	end
end

app/views/users/_custom_role_fields.html.erb
<div class="nested-fields">
	<div class="col-lg-12">
		<div class="row">
			<hr>
			<% if !first %>
			<div class="col-lg-12 col-xs-12 text-right">
				<%= link_to_remove_association "<span class='miele-text'>Eliminar Rol X</span>".html_safe, f %>
			</div>
			<% end %>
			<div class="col-md-6 col-xs-12">
				<div class="select2-role role-div select2-full-border" id="user-role">
					<%= f.select :role_id, options_for_select(@roles, f.object.role_id), { include_blank: 'Seleccione una ...', required: true}, {class: 'role' } %>
				</div>
			</div>

			<% if current_user.administrator? or current_user.manager? or f.object.sale_channel_id %>
			<div class="col-xs-12 col-md-6 <%= (f.object.sale_channel_id and (f.object.manager? or f.object.seller?)) ? '' : 'hidden' %> user-sale-channel">
				<%= f.select :sale_channel_id, options_for_select(@sale_channels.pluck(:name, :id), (f.object.try(:sale_channel_id) ? f.object.try(:sale_channel_id) : @sale_channels.first.id)), { include_blank: 'Seleccione una ...' }, class:'sale_channel' %>
			</div>
			<% end %>
			<div class="col-lg-6 col-xs-12">
				<%= f.select :cost_center_id, options_for_select(CostCenter.all.collect{ |cc| [cc.code.to_s+' - '+cc.name, cc.id] }, (f.object.try(:cost_center_id) ? f.object.try(:cost_center_id) : CostCenter.first.id)), { include_blank: 'Seleccione una ...', required: true }, class:'cost_center'%>
			</div>
		</div>
	</div>
</div>

<script>
	$('.role').select2();
	$('.cost_center').select2();
	$(".sale_channel").select2();
	$(".role").change(function(){
    var target = $(this).parent().parent().parent().parent().find('.user-sale-channel'); // perdón por el trucazo
    if($(this).val() == 2 || $(this).val() == 3){
    	target.removeClass("hidden");
    	target.first().prop("required", true);
    }
    else{
    	target.addClass("hidden");
    	target.first().prop("required", false);
    }
});
</script>

app/views/users/choose_role.html.erb
<div class="row top-login">
  <div class="col-md-8 col-xs-10 col-md-offset-2 col-xs-offset-1">
    <%= form_tag set_role_path, method: :post, id: 'select-user' do %>
    <h3 class="title-login">BIENVENIDO</h3>
    <!-- CORREO -->
    <div class="text-left field">
      <p class="role-message">Selecciona el Rol con que deseas ingresar</p>
      <%= select_tag :custom_role_id, options_for_select(@roles.collect{ |role| [role.try(:role).try(:name).to_s+' '+((role.manager? or role.seller?) ? role.try(:sale_channel).try(:name).to_s : '' ), role.id] },@roles.try(:first).try(:id)), autofocus: true, class: 'inlineb red-text', required: true %>
    </div>
    <div class="actions top-separation-login">
      <button type="submit" class="btn btn-flat-miele btn-big">Ingresar</button>
    </div>
    <% end %>
    <p class="margin-logout top-link-back"><%= link_to '<i class="fa fa-angle-left"></i> Volver al inicio de sesión'.html_safe, destroy_user_session_path, method: :delete, class: 'sign-out' %></p>
  </div>
</div>

<script>
  $("#custom_role_id").select2();
</script>

app/views/users/index.html.erb
<div class="row row-content no-bot">
	<div class="col-lg-12">
		<ol class="breadcrumb">
			<% if current_user.manager? or current_user.administrator? %>
			<li><a href="<%= root_path %>">Inicio</a></li>
			<% end %>
			<li>Usuarios</li>
		</ol>
	</div>
</div>
<div class="row bot-space">
	<div class="col-lg-6">
		<h1 class="bold title-section">
			Usuarios
		</h1>
	</div>
	<div class="col-lg-6 title-section text-right no-right">
		<% if can? :download_users, User %>
		<%= link_to 'Descargar Usuarios', download_users_path(format: :xlsx) , id: 'massive-download', class: 'btn btn-miele btn-mobile top-quotation-buttons no-loader' %>
		<% end %>
		<% if can? :upload_users, User %>
		<%= link_to 'Carga masiva de usuarios', upload_users_path , id: 'massive-load', class: 'btn btn-miele btn-mobile top-quotation-buttons' %>
		<% end %>
		<% if can? :create_user, User %>
		<%= link_to 'Crear usuario', new_user_path , id: 'new-user', class: 'btn btn-miele btn-mobile top-quotation-buttons' %>
		<% end %>
	</div>
	<div class="col-lg-3 searcher-div top-space-searcher bot-space">
		<%= form_tag(users_search_path, method: :get, id:'user-searcher-form') do %>
		  <% if can? :search_users, User %>
			<span class="hidden-lg hidden-md" id="filter-icon"><i class="fa fa-filter"></i></span>
		  <% end %>
		  <span class="input-group-addon inlineb"><i class="fa fa-search"></i></span>
		  <input type="text" name="search_user" id="search_users" class="inlineb custom-searcher-bar" autocomplete="true" placeholder="Buscar...">
		<% end %>
	</div>
	
</div>

<div class="row hidden-xs hidden-sm header-black text-center">
	<div class="col-md-1">
		<b>ID Rol</b>
	</div>
	<div class="col-md-2">
		<b>Tienda</b>
	</div>
	<div class="col-md-2">
		<b>Nombre Completo</b>
	</div>
	<div class="col-md-2">
		<b>Correo</b>
	</div>
	<div class="col-md-1">
		<b>Teléfono</b>
	</div>
	<div class="col-md-1">
		<b>Fecha de Creación</b>
	</div>
	<div class="col-md-1">
		<b>Rol</b>
	</div>
	<div class="col-md-1">
		<b>Acciones</b>
	</div>
	<div class="col-md-1">
		<% if current_user.administrator? or current_user.is_finance_manager? %>
		<b>Desactivar / Activar</b>
		<% else %>
		<b>¿Activo?</b>
		<% end %>
	</div>
</div>

<div class="row table-border">
	<% @users.each do |user| %>
	<div class="row user-row">
		<div class="col-md-1 col-xs-12">
			<b><span class="hidden-lg hidden-md">ID Rol: </span></b><%= user.try(:miele_role).try(:code) ? user.try(:miele_role).try(:code) : '<span class="miele-text">Sin información</span>'.html_safe %>
		</div>
		<div class="col-md-2 col-xs-12">
			<b><span class="hidden-lg hidden-md">Tienda: </span></b><%= user.try(:shop) ? user.try(:shop) : '<span class="miele-text">Sin información</span>'.html_safe %>
		</div>
		<div class="col-md-2 col-xs-12">
			<b><span class="hidden-lg hidden-md">Nombre Completo: </span></b><%= user.try(:list_fullname) ? user.try(:list_fullname) : '<span class="miele-text">Sin información</span>'.html_safe %>
		</div>
		<div class="col-md-2 col-xs-12">
			<b><span class="hidden-lg hidden-md">Email: </span></b><%= user.try(:email) ? user.try(:email) : '<span class="miele-text">Sin información</span>'.html_safe %>
		</div>
		<div class="col-md-1 col-xs-12">
			<b><span class="hidden-lg hidden-md">Teléfono: </span></b><%= user.try(:phone) ? user.try(:phone) : '<span class="miele-text">Sin información</span>'.html_safe %>
		</div>
		<div class="col-md-1 col-xs-12">
			<b><span class="hidden-lg hidden-md">Fecha Creación: </span></b><%= user.created_at.strftime('%d/%m/%Y') ? user.created_at.strftime('%d/%m/%Y') : '<span class="miele-text">Sin información</span>'.html_safe %>
		</div>
		<div class="col-md-1 col-xs-12">
			<b><span class="hidden-lg hidden-md">Rol: </span></b><%= user.roles_names %>
		</div>
		<div class="col-md-1 col-xs-12">
			<% if can? :edit, User %>
			<%= link_to '<i class="fa fa-user-edit"></i>'.html_safe, edit_user_path(user), class: 'miele-gray-text right-space', id: 'edit-'+user.id.to_s %>
			<% end %>
			<% if can? :destroy, User and current_user != user %>
			<%= link_to user_path(user), method: :delete, class: "miele-gray-text no-loader", id: 'delete-'+user.id.to_s, data: 
			{ confirm: '¿Estás seguro de eliminar este usuario?',
				'confirm-button-text': 'Eliminar',
				'cancel-button-text': 'Cancelar'}  do %>
				X
				<% end %>
			<% end %>
			</div>
			<div class="col-md-1 col-xs-12">

				<% if current_user.administrator? or current_user.is_finance_manager? %>
				<label class="switch">
					<input type="checkbox" name="toggle" onchange="toggleUser(<%= user.id %>)"<%= user.active ? 'checked' : '' %>>
					<span class="slider round"></span>
				</label>
				<% else %>
				<%= user.active ? 'Si' : 'No' %>
				<% end %>
			</div>
		</div>
	<% end %>
</div>
	<% page = params[:page] ? params[:page].to_i : 0 
	start = (page*10 + 1)
	%>
	<div class="row">
		<div class="col-md-5 col-xs-12 up-down-mar">
			<% if @items > 0 %>
			<% if @items < 10 %>
			<br>
			Mostrando registros del 1 al <%= @items %> de un total de <%= @items %> usuarios.
			<% else %>
			<br>
			Mostrando registros del <%= start.to_s %> al <% (start + 9).to_s %> de un total de <%= @items %> usuarios.
			<% end %>
			<% end %>
		</div>
		<div class="col-md-7 col-xs-12 pull-right text-right">
			<%= will_paginate @users, renderer: BootstrapPagination::Rails %>
		</div>
	</div>