config/routes.rb
Rails.application.routes.draw do
  resources :detail_quotation_products
  # ROOT PATH
  authenticate :user, lambda { |u| u.administrator? } do
    apipie
  end
  root 'home#index'
  # resources
  devise_for :users, :controllers => {:sessions => 'users/sessions'}
  get '/users/search', to: 'users#search'
  resources :users
  get '/choose_role', to: 'users#choose_role', as: 'choose_role'
  get '/change_role', to: 'users#change_role', as: 'change_role'
  post '/set_role', to: 'users#set_role', as: 'set_role'
  
  resources :promotional_codes
  resources :banners

  # DASHBOARD
  get '/home/filter', to: 'home#filter', as: 'filter_home'
  # BANNERS
  get '/banner/reference', to: 'banners#reference_banner', as: 'reference_banner'
  # PRODUCTOS
  get '/business_units', to: 'products#business_units', as: 'business_units'
  get  '/:business_unit/products', to: 'products#index'     , as: 'products' 
  get  '/search', to: 'products#search', as: 'search_products'
  get  '/product/:sku', to: 'products#show', as: 'product'
  get  '/product/bstock/:sku', to: 'products#show', bstock: true, as: 'bstock_product'
  patch '/product/:id', to: 'products#update', as: 'update_product'
  get '/cart/:id/mandatories_by_instalation/:instalation_id', to: 'cart#mandatories_by_instalation', as: 'mandatories_by_instalation'
  get '/bstocks', to: 'products#bstock', as: 'bstocks'
  post '/product/destroy', to: 'products#destroy', as: 'delete_product'
  patch '/product/:sku/syncronize_with_miele_core', to: 'products#synchronize_one_product_with_miele_core', as: 'synchronize_one_product_with_miele_core'
  
  # COTIZACIONES
  get 'quotations/:id/resumen'     , to: 'quotations#resumen' , as: 'quotation_resumen'
  get '/quotations/search'         , to: 'quotations#search', as: 'search_quotations'
  post '/quotations/:id/check_dispatch/:commune', to: 'quotations#check_dispatch', as: 'check_dispatch'
  post '/quotation/:id/update_payment_info', to: 'quotations#update_payment_info', as: 'update_payment_info'
  get '/quotations/:id/pay_debt', to: 'quotations#pay_debt', as: 'pay_debt'
  post '/quotation/:id/reactivate', to: 'quotations#reactivate', as: 'reactivate_quotation'
  post '/quotation/:id/reactivate_for_project', to: 'quotations#reactivate_for_project', as: 'reactivate_for_project'
  post '/quotation/:id/update_quotation', to: 'quotations#update_quotation', as: 'update_custom_quotation'
  post '/quotation/get_dispatch_cost', to: 'quotations#get_dispatch_cost'
  post '/quotation/get_dispatch_cost_show', to: 'quotations#get_dispatch_cost_show'
  post '/quotation/set_dispatch_value', to: 'quotations#set_dispatch_value'
  post '/quotation/set_installation_value', to: 'quotations#set_installation_value'
  patch '/quotation/:id/update_total_from_view', to: 'quotations#update_total_from_view'


  #normal flow
  post '/quotation/:id/finish', to: 'quotation_flow#cancel_quotation', as: 'cancel_quotation'
  post '/quotation/:id/activate', to: 'quotation_flow#activate', as: 'activate_quotation'
  post '/quotation/:id/dispatch', to: 'quotation_flow#dispatch_activation', as: 'dispatch_quotation'
  post '/quotation/:id/dispatch_confirm', to: 'quotation_flow#dispatch_confirm', as: 'dispatch_confirm_quotation'
  post '/quotation/:id/instalation', to: 'quotation_flow#instalation', as: 'instalation_quotation'
  post '/quotation/:id/activate_home_program', to: 'quotation_flow#activate_home_program', as: 'activate_home_program_quotation'
  post '/quotation/:id/load_billing_documents', to: 'quotation_flow#load_billing_documents', as: 'load_billing_documents'
  #project flow
  post '/quotation/:id/negotiation_quotation', to: 'quotation_flow#negotiation_quotation', as: 'negotiation_quotation'
  post '/quotation/:id/close_quotation', to: 'quotation_flow#close_quotation', as: 'close_quotation'
  post '/quotation/:id/lead_quotation', to: 'quotation_flow#lead_quotation', as: 'lead_quotation'
  #retail flow
  post '/quotation/:id/activate_retail', to: 'quotation_retail#activate_retail', as: 'activate_retail'
  post '/quotation/:id/activate_finance_retail', to: 'quotation_retail#activate_finance_retail', as: 'activate_finance_retail'
  post '/quotation/:id/update_quantities', to: 'quotation_retail#update_quantities', as: 'update_quantities'
  post 'quotations/:id/new_version', to: 'quotations#new_version', as: :new_version
  delete 'quotations/:id', to: 'quotations#destroy', as: :delete_version
  get 'quotations/checkout', to: 'quotations#checkout'
  post 'quotations/checkout_instalation', to: 'quotations#checkout_instalation', as: 'checkout_instalation'
  get 'quotations/:id/send_dispatch_configuration_alert', to: 'quotations#send_dispatch_configuration_alert', as: :send_dispatch_configuration_alert
  patch '/set_instalation_check', to: 'quotations#set_instalation_check'
  get 'quotations/:id/unit_real_states', to: 'quotations#get_unit_real_states'


  resources :quotations, only: [:index, :new, :create, :show, :update, :edit]
  # CARRITO
  get  '/cart', to: 'cart#index', as: 'cart'
  post  '/cart/from_quotation', to: 'cart#from_quotation', as: 'cart_from_quotation'
  post '/cart/add_mandatory_to_cart', to: 'cart#add_mandatory_to_cart', as: 'add_mandatory_to_cart'
  post '/cart/apply_discount', to: 'cart#apply_discount', as: 'apply_discount'
  post 'add_product/:id'           , to: 'cart#add_product'   , as: 'add_product_to_cart'
  post '/add_product_bstock/:id', to: 'cart#add_product_bstock', as: 'add_product_bstock'
  post 'minus_product/:id'         , to: 'cart#minus_product' , as: 'minus_product_to_cart'
  post 'plus_product/:id'          , to: 'cart#plus_product'  , as: 'plus_product_to_cart'
  delete '/cart/empty'               , to: 'cart#empty'         , as: 'empty_cart'
  delete '/remove_product/:id'     , to: 'cart#remove_product', as: 'remove_product'
  post '/change_payment/:percent'  , to: 'cart#change_percent', as: 'change_percent'
  post '/apply_promotion/:type/:id'      , to: 'cart#apply_promotion', as: 'apply_promotion'
  post '/set_dispatch/:id/:value', to: 'cart#set_dispatch', as: 'set_dispatch'
  post '/set_instalation/:id', to: 'cart#set_instalation', as: 'set_instalation'
  get 'cart/update_totals'
  post 'cart/update_item_price'
  post 'cart_items/calculate_margen', to: "cart#calculate_margen"

  #carga de datos
  get '/data_upload'               , to: 'data_upload#upload_info', as: 'upload_info'
  post '/upload/product_photos'    , to: 'data_upload#load_photos', as: 'upload_product_photos'
  post '/upload/mandatory_products', to: 'data_upload#load_mandatory', as: 'upload_mandatory'
  post '/upload/products'          , to: 'data_upload#load_products', as: 'upload_products'
  post '/upload/discounts', to: 'data_upload#load_discounts', as: 'upload_discounts'
  post '/upload/addressees', to: 'data_upload#load_addressees', as: 'upload_addressees'
  post '/upload/stock', to: 'data_upload#load_stock', as: 'upload_stock'
  post '/upload/technical_images', to: 'data_upload#load_technical_images', as: 'upload_technical_images'
  post '/upload/load_comparator_info', to: 'data_upload#load_comparator_info', as: 'load_comparator_info'
  post '/upload/load_homologate_tnr', to: 'data_upload#load_homologate_tnr', as: 'load_homologate_tnr'
  post 'upload/load_oc_retail', to: 'data_upload#load_oc_retail', as: 'load_oc_retail'
  post 'upload/load_quotation_project', to: 'data_upload#load_quotation_project', as: 'load_quotation_project'
  post 'upload/load_cost_center', to: 'data_upload#load_cost_center', as: 'load_cost_center'
  post '/upload/load_miele_roles', to: 'data_upload#load_miele_roles', as: 'load_miele_roles'
  post '/upload/commission_levels', to: 'data_upload#load_commission_levels', as: 'load_commission_levels'
  post '/upload/load_project_installation_value', to: 'data_upload#load_project_installation_value', as: 'load_project_installation_value'
  post '/upload/load_project_installation_discount', to: 'data_upload#load_project_installation_discount', as: 'load_project_installation_discount'
  post '/upload/load_dispatch_rule', to: 'data_upload#load_dispatch_rule', as: 'load_dispatch_rule'
  post '/upload/save_margen', to: 'data_upload#load_save_margen', as: 'load_save_margen'


  patch '/update/customer_core_ids', to: 'data_upload#update_customer_core_ids', as: 'update_customer_core_ids'
  patch '/update/product_core_ids', to: 'data_upload#update_product_core_ids', as: 'update_product_core_ids'
  patch '/update/synchronizeProductsWithMieleCore', to: 'data_upload#synchronizeProductsWithMieleCore', as: 'synchronize_products_with_miele_core'

  get '/download/stock', to: 'data_upload#download_stock', as: 'download_stock'
  get '/download/products_template', to: 'data_upload#download_products', as: 'download_products'
  get '/download/discounts', to: 'data_upload#download_discounts', as: 'download_discounts'
  get '/download/addressees', to: 'data_upload#download_addressees', as: 'download_addressees'
  get '/download/commissions_table', to: 'data_upload#download_commissions_table', as: 'download_commissions_table'
  get '/download/cost_center', to: 'data_upload#download_cost_center', as: 'download_cost_center'
  get '/download/miele_roles', to: 'data_upload#download_miele_roles', as: 'download_miele_roles'
  get '/download/tnr_homologated', to: 'data_upload#download_tnr_homologated', as: 'download_tnr_homologated'
  #usuarios
  get '/upload_users', to: 'users#upload_users', as: 'upload_users'
  post '/load_users', to: 'users#load_users', as: 'load_users'
  post '/users/create_user' => 'users#create_user'
  post '/user/toggle/:id', to: 'users#toggle', as: 'toggle_user'
  get '/download/users', to: 'users#download_users', as: 'download_users'
  #clientes
  get '/customers/search', to: 'customers#search', as: 'search_customer'
  get '/clientes', to: 'customers#search_tracking', as: 'search_tracking'
  get '/busqueda', to: 'customers#find_by_rut_and_code', as: 'find_by_rut_and_code'
  #templates

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		if current_user.foreign? or current_user.seller?
			redirect_to business_units_path
		elsif current_user.manager?
			@quotations = current_user.sale_channel.quotations.order("updated_at DESC").limit(5)
			@quotations_by_state = Dashboard.quotations_by_state(current_user)
			@quotations_per_channel = Dashboard.quotations_per_channel(current_user)
			@products_most_selled = Dashboard.products_most_selled(current_user)
			@quotations_per_channel_and_product_type = Dashboard.quotation_products_per_channel_and_product_type(current_user)
		elsif current_user.administrator? or current_user.is_manager_inventory?
			@quotations = Quotation.all.order("updated_at DESC").limit(5)
			@quotations_by_state = Dashboard.quotations_by_state(current_user)
			@quotations_per_channel = Dashboard.quotations_per_channel(current_user)
			@products_most_selled = Dashboard.products_most_selled(current_user)
			@quotations_per_channel_and_product_type = Dashboard.quotation_products_per_channel_and_product_type(current_user)
		else
			redirect_to quotations_path
		end
	end

	def filter
		range_date = params[:date_range].split(' - ')
		start_date = DateTime.parse(range_date[0]).beginning_of_day
		end_date = DateTime.parse(range_date[1]).end_of_day
		@quotations_by_state = Dashboard.quotations_by_state(current_user, start_date, end_date)
		@quotations_per_channel = Dashboard.quotations_per_channel(current_user, start_date, end_date)
		@products_most_selled = Dashboard.products_most_selled(current_user, start_date, end_date)
		respond_to do |format|
			format.js
		end
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_quotations_per_state.html.erb
<p class="dashboard-title">Cotizaciones Enviadas v/s Cerradas</p>
<figure class="highcharts-figure">
	<div id="quotations-per-state-container"></div>
</figure>

<script>
	var data = <%= @quotations_by_state.to_json.html_safe %>;
	Highcharts.chart('quotations-per-state-container', {
		chart: {
			type: 'column'
		},
		title: {
			text: ''
		},
		xAxis: {
			categories: data.categories
		},
		yAxis: {
			min: 0,
			title: {
				text: 'Cotizaciones'
			},
			stackLabels: {
				enabled: true,
				style: {
					fontWeight: 'bold',
                color: ( // theme
                	Highcharts.defaultOptions.title.style &&
                	Highcharts.defaultOptions.title.style.color
                	) || 'gray'
            }
        }
    },
    legend: {
    	align: 'right',
    	x: -30,
    	verticalAlign: 'top',
    	y: 25,
    	floating: true,
    	backgroundColor:
    	Highcharts.defaultOptions.legend.backgroundColor || 'white',
    	borderColor: '#CCC',
    	borderWidth: 1,
    	shadow: false
    },
    tooltip: {
    	headerFormat: '<b>{point.x}</b><br/>',
    	pointFormat: '{series.name}: {point.y}<br/>Total: {point.stackTotal}'
    },
    plotOptions: {
    	column: {
    		stacking: 'normal',
    		dataLabels: {
    			enabled: true
    		}
    	}
    },
    credits: {
        enabled: false
    },
    series: data.data
});
</script>

app/views/home/_sales_per_channel_and_cost_center.html.erb
<p class="dashboard-title">Ventas <%= current_user.administrator? ? 'Por Áreas y Centro de Costo' : '' %></p>
<figure class="highcharts-figure">
	<div id="chart-channels"></div>
</figure>

<script>
	// Create the chart
	Highcharts.chart('chart-channels', {
		lang: {
			drillUpText: 'Volver'
		},
		chart: {
			type: 'column'
		},
		title: {
			text: ''
		},
		subtitle: {
			text: ''
		},
		accessibility: {
			announceNewData: {
				enabled: true
			}
		},
		xAxis: {
			type: 'category'
		},
		yAxis: {
			title: {
				text: 'Monto $'
			}

		},
		legend: {
			enabled: false
		},
		plotOptions: {
			series: {
				borderWidth: 0,
				dataLabels: {
					enabled: true,
					format: '$ {point.y:,.0f}'
				}
			}
		},

		tooltip: {
			headerFormat: '<span style="font-size:11px">{series.name}</span><br>',
			pointFormat: '<span style="color:{point.color}">{point.name}</span>: <b>$ {point.y:,.0f}</b><br/>',
			shared: true,
			useHTML: true
		},
		credits: {
			enabled: false
		},

		series: [<%= @quotations_per_channel[:data].to_json.html_safe %>],
		drilldown: <%= @quotations_per_channel[:drilldown].to_json.html_safe %>
	});
</script>

app/views/home/_sales_per_channel_and_product_type.html.erb
<p class="dashboard-title">Ventas por Canal y Tipo de producto</p>
<figure class="highcharts-figure">
	<div id="sales-per-channel-and-product-type"></div>
</figure>

<script>
	var data = <%= @quotations_per_channel_and_product_type.to_json.html_safe %>;
	Highcharts.chart('sales-per-channel-and-product-type', {
		chart: {
			type: 'column'
		},
		title: {
			text: ''
		},
		xAxis: {
			categories: data.categories
		},
		yAxis: {
			min: 0,
			title: {
				text: 'Monto $'
			},
			stackLabels: {
				enabled: true,
				style: {
					fontWeight: 'bold',
					color: ( // theme
						Highcharts.defaultOptions.title.style &&
						Highcharts.defaultOptions.title.style.color
						) || 'gray'
            	},
				format: '$ {total:,.0f}'
        	}
    	},
    legend: {
    	align: 'right',
    	x: -30,
    	verticalAlign: 'top',
    	y: -10,
    	floating: true,
    	backgroundColor:
    	Highcharts.defaultOptions.legend.backgroundColor || 'white',
    	borderColor: '#CCC',
    	borderWidth: 1,
    	shadow: false
    },
    tooltip: {
    	headerFormat: '<b>{point.x}</b><br/>',
    	pointFormat: '{series.name}: $ {point.y:,.0f}<br/>Total: $ {point.stackTotal:,.0f}'
    },
    plotOptions: {
    	column: {
    		stacking: 'normal',
    		dataLabels: {
    			enabled: true,
				formatter: function () {
					let column_total = this.point.y/ 1000000.0;
					let formatted_total = column_total < 1.0 ? column_total.toFixed(2) : Math.round(column_total); 
                	return "$ " + formatted_total + " MM";
            	}

    		}
    	}
    },
    credits: {
        enabled: false
    },
    series: data.data
});
</script>

app/views/home/_top_10_products.html.erb
<p class="dashboard-title">Productos Más Vendidos v/s Cotizados</p>
<figure class="highcharts-figure">
	<div id="top-10-div"></div>
</figure>

<script>
	var data = <%= @products_most_selled.to_json.html_safe %>
	Highcharts.chart('top-10-div', {
		chart: {
			type: 'bar'
		},
		title: {
			text: ''
		},
		xAxis: {
			categories: data.categories,
			title: {
				text: 'Producto'
			}
		},
		yAxis: {
			min: 0,
			title: {
				text: 'Unidades',
				align: 'high'
			},
			labels: {
				overflow: 'justify'
			}
		},
		plotOptions: {
			bar: {
				dataLabels: {
					enabled: true
				}
			}
		},
		legend: {
			layout: 'vertical',
			align: 'right',
			verticalAlign: 'top',
			x: -40,
			y: 250,
			floating: true,
			borderWidth: 1,
			backgroundColor:
			Highcharts.defaultOptions.legend.backgroundColor || '#FFFFFF',
			shadow: true
		},
		credits: {
			enabled: false
		},
		series: data.data,
		responsive: {
			rules: [{
				condition: {
					maxWidth: 600
				},
				chartOptions: {
					legend: {
						enabled: false
					}
				}
			}]
		}
	});
</script>

app/views/home/filter.js.erb
$("#quotations-state").html('<%= j render partial: "home/quotations_per_state" %>');
$("#sales-channels").html('<%= j render partial: "home/sales_per_channel_and_cost_center" %>');
$("#top-products").html('<%= j render partial: "home/top_10_products" %>');
$(".loader-page").fadeOut("slow");

app/views/home/index.html.erb
<div class="row bot-space top-space-home">
	<div class="col-lg-5 col-xs-12">
		<h1 class="bold">
			Dashboard <%= current_user.administrator? ? 'Administrador' : 'Manager' %>
		</h1>
	</div>
	<div class="col-lg-2 col-lg-offset-5 col-xs-12">
		<%= form_tag(filter_home_path, method: :get, remote: true, id: 'filter-form') do %>
		<label for="filter" class="label-text">Inicio - Fin</label>
		<input type="text" class="inlineb date-range gray-background" name="date_range" id="date_range">
		<% end %>
	</div>
</div>
<div class="row">
	<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
		<div class="dashboard-panel" id="quotations-state">
			<%= render 'home/quotations_per_state' %>
		</div>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
		<div class="dashboard-panel" id="sales-channels">
			<%= render 'home/sales_per_channel_and_cost_center' %>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
		<div class="dashboard-panel">
			<%= render 'home/sales_per_channel_and_product_type' %>
		</div>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
		<div class="dashboard-panel" id="top-products">
			<%= render 'home/top_10_products' %>
		</div>
	</div>
</div>
<% if can? :index, Quotation %>
<div class="row bot-space top-space-home">
	<div class="col-lg-5 col-xs-12">
		<h3>
			Últimas cotizaciones
			<%= link_to 'Ver todas', quotations_path, class: 'btn btn-miele left-mar' %>
		</h3>
	</div>
</div>

<div class="row">
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
		<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
			<% @quotations.each_with_index do |quotation, index| %>
			<% if quotation.channel == 'Retail' %>
				<%= render partial: 'quotations/quotation_card_retail', locals: {quotation: quotation} %>
			<% else %>
				<%= render partial: 'quotations/quotation_card', locals: {quotation: quotation} %>
			<% end %>
			<% end %>
		</div>
	</div>
</div>
<% end %>
<script>
	$(document).ready(function(){
		$("#date_range").val('<%= "#{(Date.today - 3.months).strftime('%d/%m/%Y')} - #{Date.today.strftime('%d/%m/%Y')}" %>');
	});
	$(document).ready(function(){
		$('.date-range').daterangepicker({
			"autoUpdateInput": true,
			"minDate": new Date(2012, 0, 1),
			"locale": {
				"format": "DD/MM/YYYY",
				"separator": " - ",
				"applyLabel": "Guardar",
				"cancelLabel": "Cancelar",
				"fromLabel": "Desde",
				"toLabel": "Hasta",
				"customRangeLabel": "Custom",
				"weekLabel": "S",
				"daysOfWeek": [
				"Do",
				"Lu",
				"Ma",
				"Mi",
				"Ju",
				"Vi",
				"Sa"
				],
				"monthNames": [
				"Enero",
				"Febrero",
				"Marzo",
				"Abril",
				"Mayo",
				"Junio",
				"Julio",
				"Agosto",
				"Septiembre",
				"Octubre",
				"Noviembre",
				"Diciembre"
				],
				"firstDay": 1
			},
			"cancelClass": "btn-secondary",
			"applyClass": "btn-miele",
			"singleDatePicker": false
		}, function(init_date, end_date) {
			$('.date-range').val(init_date.format('DD/MM/YYYY')+' - '+end_date.format('DD/MM/YYYY'));
			$(".date-range").trigger('change');
		});
		$("#filter-form").change(function(){
			var dates = $("#date_range").val().split(' - ');
			$(this).submit();
			$(".loader-page").fadeIn();
		});
	}); 
	$(".row-toggle-quotation").click(function(){
		if($(this).hasClass('open-quotation')){
			$(this).removeClass('open-quotation');
		} else {
			$(this).addClass('open-quotation');
		}
	});
	$('.panel-collapse').on('show.bs.collapse', function () {
		$(this).siblings('.panel-heading').addClass('active');
	});

	$('.panel-collapse').on('hide.bs.collapse', function () {
		$(this).siblings('.panel-heading').removeClass('active');
	});
</script>