config/routes.rb
Rails.application.routes.draw do
  resources :detail_quotation_products
  # ROOT PATH
  authenticate :user, lambda { |u| u.administrator? } do
    apipie
  end
  root 'home#index'
  # resources
  devise_for :users, :controllers => {:sessions => 'users/sessions'}
  get '/users/search', to: 'users#search'
  resources :users
  get '/choose_role', to: 'users#choose_role', as: 'choose_role'
  get '/change_role', to: 'users#change_role', as: 'change_role'
  post '/set_role', to: 'users#set_role', as: 'set_role'
  
  resources :promotional_codes
  resources :banners

  # DASHBOARD
  get '/home/filter', to: 'home#filter', as: 'filter_home'
  # BANNERS
  get '/banner/reference', to: 'banners#reference_banner', as: 'reference_banner'
  # PRODUCTOS
  get '/business_units', to: 'products#business_units', as: 'business_units'
  get  '/:business_unit/products', to: 'products#index'     , as: 'products' 
  get  '/search', to: 'products#search', as: 'search_products'
  get  '/product/:sku', to: 'products#show', as: 'product'
  get  '/product/bstock/:sku', to: 'products#show', bstock: true, as: 'bstock_product'
  patch '/product/:id', to: 'products#update', as: 'update_product'
  get '/cart/:id/mandatories_by_instalation/:instalation_id', to: 'cart#mandatories_by_instalation', as: 'mandatories_by_instalation'
  get '/bstocks', to: 'products#bstock', as: 'bstocks'
  post '/product/destroy', to: 'products#destroy', as: 'delete_product'
  patch '/product/:sku/syncronize_with_miele_core', to: 'products#synchronize_one_product_with_miele_core', as: 'synchronize_one_product_with_miele_core'
  
  # COTIZACIONES
  get 'quotations/:id/resumen'     , to: 'quotations#resumen' , as: 'quotation_resumen'
  get '/quotations/search'         , to: 'quotations#search', as: 'search_quotations'
  post '/quotations/:id/check_dispatch/:commune', to: 'quotations#check_dispatch', as: 'check_dispatch'
  post '/quotation/:id/update_payment_info', to: 'quotations#update_payment_info', as: 'update_payment_info'
  get '/quotations/:id/pay_debt', to: 'quotations#pay_debt', as: 'pay_debt'
  post '/quotation/:id/reactivate', to: 'quotations#reactivate', as: 'reactivate_quotation'
  post '/quotation/:id/reactivate_for_project', to: 'quotations#reactivate_for_project', as: 'reactivate_for_project'
  post '/quotation/:id/update_quotation', to: 'quotations#update_quotation', as: 'update_custom_quotation'
  post '/quotation/get_dispatch_cost', to: 'quotations#get_dispatch_cost'
  post '/quotation/get_dispatch_cost_show', to: 'quotations#get_dispatch_cost_show'
  post '/quotation/set_dispatch_value', to: 'quotations#set_dispatch_value'
  post '/quotation/set_installation_value', to: 'quotations#set_installation_value'
  patch '/quotation/:id/update_total_from_view', to: 'quotations#update_total_from_view'


  #normal flow
  post '/quotation/:id/finish', to: 'quotation_flow#cancel_quotation', as: 'cancel_quotation'
  post '/quotation/:id/activate', to: 'quotation_flow#activate', as: 'activate_quotation'
  post '/quotation/:id/dispatch', to: 'quotation_flow#dispatch_activation', as: 'dispatch_quotation'
  post '/quotation/:id/dispatch_confirm', to: 'quotation_flow#dispatch_confirm', as: 'dispatch_confirm_quotation'
  post '/quotation/:id/instalation', to: 'quotation_flow#instalation', as: 'instalation_quotation'
  post '/quotation/:id/activate_home_program', to: 'quotation_flow#activate_home_program', as: 'activate_home_program_quotation'
  post '/quotation/:id/load_billing_documents', to: 'quotation_flow#load_billing_documents', as: 'load_billing_documents'
  #project flow
  post '/quotation/:id/negotiation_quotation', to: 'quotation_flow#negotiation_quotation', as: 'negotiation_quotation'
  post '/quotation/:id/close_quotation', to: 'quotation_flow#close_quotation', as: 'close_quotation'
  post '/quotation/:id/lead_quotation', to: 'quotation_flow#lead_quotation', as: 'lead_quotation'
  #retail flow
  post '/quotation/:id/activate_retail', to: 'quotation_retail#activate_retail', as: 'activate_retail'
  post '/quotation/:id/activate_finance_retail', to: 'quotation_retail#activate_finance_retail', as: 'activate_finance_retail'
  post '/quotation/:id/update_quantities', to: 'quotation_retail#update_quantities', as: 'update_quantities'
  post 'quotations/:id/new_version', to: 'quotations#new_version', as: :new_version
  delete 'quotations/:id', to: 'quotations#destroy', as: :delete_version
  get 'quotations/checkout', to: 'quotations#checkout'
  post 'quotations/checkout_instalation', to: 'quotations#checkout_instalation', as: 'checkout_instalation'
  get 'quotations/:id/send_dispatch_configuration_alert', to: 'quotations#send_dispatch_configuration_alert', as: :send_dispatch_configuration_alert
  patch '/set_instalation_check', to: 'quotations#set_instalation_check'
  get 'quotations/:id/unit_real_states', to: 'quotations#get_unit_real_states'


  resources :quotations, only: [:index, :new, :create, :show, :update, :edit]
  # CARRITO
  get  '/cart', to: 'cart#index', as: 'cart'
  post  '/cart/from_quotation', to: 'cart#from_quotation', as: 'cart_from_quotation'
  post '/cart/add_mandatory_to_cart', to: 'cart#add_mandatory_to_cart', as: 'add_mandatory_to_cart'
  post '/cart/apply_discount', to: 'cart#apply_discount', as: 'apply_discount'
  post 'add_product/:id'           , to: 'cart#add_product'   , as: 'add_product_to_cart'
  post '/add_product_bstock/:id', to: 'cart#add_product_bstock', as: 'add_product_bstock'
  post 'minus_product/:id'         , to: 'cart#minus_product' , as: 'minus_product_to_cart'
  post 'plus_product/:id'          , to: 'cart#plus_product'  , as: 'plus_product_to_cart'
  delete '/cart/empty'               , to: 'cart#empty'         , as: 'empty_cart'
  delete '/remove_product/:id'     , to: 'cart#remove_product', as: 'remove_product'
  post '/change_payment/:percent'  , to: 'cart#change_percent', as: 'change_percent'
  post '/apply_promotion/:type/:id'      , to: 'cart#apply_promotion', as: 'apply_promotion'
  post '/set_dispatch/:id/:value', to: 'cart#set_dispatch', as: 'set_dispatch'
  post '/set_instalation/:id', to: 'cart#set_instalation', as: 'set_instalation'
  get 'cart/update_totals'
  post 'cart/update_item_price'
  post 'cart_items/calculate_margen', to: "cart#calculate_margen"

  #carga de datos
  get '/data_upload'               , to: 'data_upload#upload_info', as: 'upload_info'
  post '/upload/product_photos'    , to: 'data_upload#load_photos', as: 'upload_product_photos'
  post '/upload/mandatory_products', to: 'data_upload#load_mandatory', as: 'upload_mandatory'
  post '/upload/products'          , to: 'data_upload#load_products', as: 'upload_products'
  post '/upload/discounts', to: 'data_upload#load_discounts', as: 'upload_discounts'
  post '/upload/addressees', to: 'data_upload#load_addressees', as: 'upload_addressees'
  post '/upload/stock', to: 'data_upload#load_stock', as: 'upload_stock'
  post '/upload/technical_images', to: 'data_upload#load_technical_images', as: 'upload_technical_images'
  post '/upload/load_comparator_info', to: 'data_upload#load_comparator_info', as: 'load_comparator_info'
  post '/upload/load_homologate_tnr', to: 'data_upload#load_homologate_tnr', as: 'load_homologate_tnr'
  post 'upload/load_oc_retail', to: 'data_upload#load_oc_retail', as: 'load_oc_retail'
  post 'upload/load_quotation_project', to: 'data_upload#load_quotation_project', as: 'load_quotation_project'
  post 'upload/load_cost_center', to: 'data_upload#load_cost_center', as: 'load_cost_center'
  post '/upload/load_miele_roles', to: 'data_upload#load_miele_roles', as: 'load_miele_roles'
  post '/upload/commission_levels', to: 'data_upload#load_commission_levels', as: 'load_commission_levels'
  post '/upload/load_project_installation_value', to: 'data_upload#load_project_installation_value', as: 'load_project_installation_value'
  post '/upload/load_project_installation_discount', to: 'data_upload#load_project_installation_discount', as: 'load_project_installation_discount'
  post '/upload/load_dispatch_rule', to: 'data_upload#load_dispatch_rule', as: 'load_dispatch_rule'
  post '/upload/save_margen', to: 'data_upload#load_save_margen', as: 'load_save_margen'


  patch '/update/customer_core_ids', to: 'data_upload#update_customer_core_ids', as: 'update_customer_core_ids'
  patch '/update/product_core_ids', to: 'data_upload#update_product_core_ids', as: 'update_product_core_ids'
  patch '/update/synchronizeProductsWithMieleCore', to: 'data_upload#synchronizeProductsWithMieleCore', as: 'synchronize_products_with_miele_core'

  get '/download/stock', to: 'data_upload#download_stock', as: 'download_stock'
  get '/download/products_template', to: 'data_upload#download_products', as: 'download_products'
  get '/download/discounts', to: 'data_upload#download_discounts', as: 'download_discounts'
  get '/download/addressees', to: 'data_upload#download_addressees', as: 'download_addressees'
  get '/download/commissions_table', to: 'data_upload#download_commissions_table', as: 'download_commissions_table'
  get '/download/cost_center', to: 'data_upload#download_cost_center', as: 'download_cost_center'
  get '/download/miele_roles', to: 'data_upload#download_miele_roles', as: 'download_miele_roles'
  get '/download/tnr_homologated', to: 'data_upload#download_tnr_homologated', as: 'download_tnr_homologated'
  #usuarios
  get '/upload_users', to: 'users#upload_users', as: 'upload_users'
  post '/load_users', to: 'users#load_users', as: 'load_users'
  post '/users/create_user' => 'users#create_user'
  post '/user/toggle/:id', to: 'users#toggle', as: 'toggle_user'
  get '/download/users', to: 'users#download_users', as: 'download_users'
  #clientes
  get '/customers/search', to: 'customers#search', as: 'search_customer'
  get '/clientes', to: 'customers#search_tracking', as: 'search_tracking'
  get '/busqueda', to: 'customers#find_by_rut_and_code', as: 'find_by_rut_and_code'
  #templates

app/controllers/api/v1/quotations_controller.rb
class Api::V1::QuotationsController < ApplicationController
    skip_before_action :authenticate_user!
    before_action :authenticate

    before_action :set_quotation, only: [:get_current_status]

    api :GET, "/v1/quotations/:id/current_status", "Muestra el estado actual de una cotización"
    param :id, String, :desc => "ID de la cotización a consultar el estado actual"
    
    def get_current_status
        if @quotation
            response = { status: @quotation.get_state }
            render json: response.to_json, status: :ok
        else 
            response = { error: 'Not found' }
            render json: response.to_json, status: :not_found
        end
    end

    private

    def set_quotation
        @quotation = Quotation.find_by(id: params[:id])
    end
end

app/helpers/quotations_helper.rb
module QuotationsHelper
	def get_state_label(state, size)
		return nil unless state
		if size == "full"
			size_label = ""
		else
			size_label = "mini-label"
		end
		case state.name
		when "Enviada"
			return "<span class='state-label #{size_label} sent-state' data-toggle='tooltip' title='La cotización ha sido enviada al cliente.'>Enviada</span>".html_safe
		when "En curso"
			return "<span class='state-label #{size_label} progress-state' data-toggle='tooltip' title='La cotización ha sido enviada a finanzas para su revisión.'>En curso</span>".html_safe
		when "Pendiente"
			return "<span class='state-label #{size_label} pending-state' data-toggle='tooltip' title='El área de finanzas ha confirmado el pago parcial de esta cotización.'>Pendiente</span>".html_safe
		when "En preparación", "Despachos e Instalaciones"
			return "<span class='state-label #{size_label} preparation-state' data-toggle='tooltip' title='La cotización está siendo procesada para su despacho e instalación.'>#{state.name}</span>".html_safe
		when "Cerrado"
			return "<span class='state-label #{size_label} closed-state' data-toggle='tooltip' title='Cotización finalizada.'>Cerrado</span>".html_safe
		when "Vencida"
			return "<span class='state-label #{size_label} expired-state' data-toggle='tooltip' title='Han transcurrido los 30 días de validez para esta cotización.'>Vencida</span>".html_safe
		when "Despachado"
			return "<span class='state-label #{size_label} dispatched-state' data-toggle='tooltip' title='Se ha generado la guía de despacho para esta cotización.'>Despachado</span>".html_safe
		when "Entregado"
			return "<span class='state-label #{size_label} delivered-state' data-toggle='tooltip' title='Los productos han sido entregados al cliente.'>Entregado</span>".html_safe
		when "Por instalar"
			return "<span class='state-label #{size_label} instalation-pending-state' data-toggle='tooltip' title='Los productos han sido entregados y están pendientes de instalación.'>Por Instalar</span>".html_safe
		when "Entrega Pendiente"
			return "<span class='state-label #{size_label} pending-delivery-state' data-toggle='tooltip' title='Los productos están en camino al cliente.'>Entrega Pendiente</span>".html_safe
		when "Instalado"
			return "<span class='state-label #{size_label} instaled-state' data-toggle='tooltip' title='Los productos ya han sido instalados.'>Instalado</span>".html_safe
		when "Instalación Pendiente"
			return "<span class='state-label #{size_label} pending-instalation-state' data-toggle='tooltip' title='Los productos están pendientes de instalación.'>Instalación Pendiente</span>".html_safe
		when "Por activar"
			return "<span class='state-label #{size_label} pending-activation-state' data-toggle='tooltip' title='Los productos están pendientes de activación.'>Por activar</span>".html_safe
		when "Productos activados"
			return "<span class='state-label #{size_label} actived-products-state' data-toggle='tooltip' title='Los productos han sido activados.'>Productos activados</span>".html_safe
		when "Ingresada"
			return "<span class='state-label #{size_label} oc-first-state' data-toggle='tooltip' title='La orden de compra (OC) ha sido ingresada.'>Ingresada</span>".html_safe
		when "Cancelada"
			return "<span class='state-label #{size_label} cancel-state' data-toggle='tooltip' title='La cotización ha sida cancelada.'>Cancelada</span>".html_safe
		when "En Negociación"
			return "<span class='state-label #{size_label} negotiation-state' data-toggle='tooltip' title='La cotización está en proceso de negociación.'>En Negociación</span>".html_safe
		when "Lead"
			return "<span class='state-label #{size_label} lead-state' data-toggle='tooltip' title='Lead con datos de posible cliente.'>Lead</span>".html_safe
		when "Finalizado"
			return "<span class='state-label #{size_label} dispatched-state' data-toggle='tooltip' title='Finalizado con éxito'>Finalizado</span>".html_safe
		end
	end

	def get_title(current_user)
		if current_user.is_finance_manager? or current_user.is_finance?
			return 'Mis ventas'.html_safe
		elsif current_user.is_dispatch? or current_user.is_manager_dispatch?
			return 'Mis despachos'.html_safe
		elsif current_user.is_instalation? or current_user.is_manager_instalation?
			return 'Mis instalaciones'.html_safe
		elsif current_user.is_retail?
			return 'Mis OC'.html_safe
		else
			return 'Mis cotizaciones'.html_safe
		end
	end

	def get_name_quotation(current_user)
		if current_user.is_finance_manager? or current_user.is_finance?
			return 'venta'.html_safe
		elsif current_user.is_dispatch? or current_user.is_manager_dispatch?
			return 'despacho'.html_safe
		elsif current_user.is_instalation? or current_user.is_manager_instalation?
			return 'instalación'.html_safe
		elsif current_user.is_retail?
			return 'OC'.html_safe
		else
			return 'cotización'.html_safe
		end
	end

	def can_delete_docs(quotation)
		["Enviada", "Ingresada", "En curso", "Pendiente","En Negociación", "Lead"].include?(quotation.get_state)
	end

	def dispatch_partial_by_state(state_name)
		case state_name
			when 'En preparación'
				return 'quotations/dispatch/in_preparation'
			when 'Despachado'
				return 'quotations/dispatch/dispatched'
			else
				return 'quotations/dispatch/show'
		end
	end

	def quotation_currency_from_params
		if params[:currency].present?
			return params[:currency]
		else
			return @quotation.currency
		end
	end

	def quotation_exchange_rate_from_params
		if params[:exchange_rate].present?
			return params[:exchange_rate]
		else
			return @quotation.exchange_rate
		end
	end

	def quotation_exchange_rate_date_from_params
		if params[:exchange_rate_date].present?
			return params[:exchange_rate_date]
		else
			return @quotation.exchange_rate_date
		end
	end

	def display_quotation_currency(currency)
		case currency
			when 'clp'
				return '$'
			when 'usd', 'uf'
				return currency
			else
				return '$'
		end
	end

	def quotation_form_by_role
		if current_user.can_manage_project_quotations?
			return 'quotations/form/project_quotation'
		else
			return 'quotations/form/normal_quotation'
		end
	end

	def customer_tab_by_channel(channel)
		case channel
			when 'Retail'
				return 'quotations/customer_tab/retail'
			when 'Proyectos'
				return 'quotations/customer_tab/project'
			else
				return 'quotations/customer_tab/normal'
		end
	end

	def customer_tab_label_by_channel(channel)
		case channel
			when 'Proyectos'
				return 'Datos Proyecto'
			else
				return 'Datos Cliente'
		end
	end
end

app/views/quotations/_quotation_card.html.erb
  <div class="panel panel-default mini-bot-space border-<%= quotation.get_state.downcase.gsub(' ', '-') %> quotation-card">
  	<% if !quotation.sale_channel.nil?%>
      <% if quotation.sale_channel.name == "E-commerce"%>
        <div class="ecommerce-card"></div>
      <% end %>
    <% end %>
    <div class="panel-heading normal-alert" role="tab" id="headingTwo">
  		<div class="row">
        <div class="col-lg-2 col-md-2 hidden-xs hidden-sm">
  				<p><b>Última actualización</b></p>
  				<p class="light-quotation"><%= quotation.updated_at.strftime('%Y-%m-%d %H:%M') %></p>
  			</div>      
  			<div class="col-lg-1 col-md-1 col-sm-4 col-xs-4">
  				<p><b>Código</b></p>
  				<p class="light-quotation"><%= quotation.code %></p>
  			</div>
  			<div class="col-lg-2 col-md-2 col-sm-4 col-xs-4">
  				<p><b>Cliente</b></p>
  				<p class="light-quotation"><%= quotation.customer_name %></p>
  			</div>
  			<div class="col-lg-1 col-md-1 hidden-xs hidden-sm">
  				<p><b>RUT</b></p>
  				<p class="light-quotation"><%= quotation.rut %></p>
  			</div>
  			<div class="<%= ((((current_user.administrator? or current_user.manager?) and quotation.partner_commission)) or quotation.user.is_mca?) ? 'col-lg-2 col-md-2' : 'col-lg-4 col-md-4' %> hidden-xs hidden-sm">
  				<p><b>Correo</b></p>
  				<p class="light-quotation"><%= quotation.email %></p>
  			</div>
        <% show = true %>
        <% if (current_user.administrator? or current_user.manager?) and quotation.partner_commission %>
          <div class="col-lg-2 col-md-2 hidden-xs hidden-sm">
            <p><b>Comisión <%= quotation.try(:partner_selected_commission).try(:code) %></b></p>
            <p class="light-quotation"><%= number_to_currency(quotation.partner_commission) %> <span class="mini-text-gray">(IVA Incluído)</span></p>
          </div>
  			<% elsif quotation.user.is_mca? %>
          <% show = false %>
          <div class="col-lg-2 col-md-2 hidden-xs hidden-sm">
            <p><b>Comisión Vendedor</b></p>
            <p class="light-quotation"><%= number_to_currency(quotation.mca_commission) %> <span class="mini-text-gray">(IVA Incluído)</span></p>
  			  </div>
  			<% end %>
  			<div class="col-lg-1 col-md-1 hidden-xs hidden-sm no-sides-all">
  				<p><b>Estado</b></p>
  				<p class="light-quotation"><%= get_state_label(quotation.quotation_state, 'mini') %></p>
  			</div>
  			<div class="col col-lg-1 col-md-2 col-sm-3 col-xs-4 inlineb text-right no-left-mobile vertical-icons">
          <% if quotation.get_state == 'Enviada' %>
          <%= link_to cart_from_quotation_path(id: quotation.id), method: :post do %>
          <%= image_tag('edit.svg', class: 'loop-icon inlineb right-space-icon moving-top', size: '26x18')%>
          <% end %>
          <% end %>
          <% if can? :reactivate, Quotation %>
          <% if quotation.get_state == 'Vencida' %>
          <%= link_to reactivate_quotation_path(quotation), id: 'reactivate-quotation', method: :post, data: 
          { confirm: '¿Está seguro que desea reactivar esta cotización?',
            'text': 'Los precios y promociones serán actualizados al día de hoy',
            'image-url': 'https://icons-for-free.com/iconfiles/png/512/refresh+reload+update+icon-1320191166843452904.png',
            'image-width': 50,
            'image-height': 50,
            'image-alt': 'icono',
            'confirm-button-text': 'Aceptar',
            'cancel-button-text': 'Cancelar'} do %>
            <%= image_tag('loop.svg', class: 'loop-icon inlineb right-space-icon moving-top')%>
            <% end %>
            <% end %>
            <% end %>
            <%= link_to quotation_path(quotation), class:'show-eye inlineb' do %>
            <%= image_tag('eye-icon.svg', class: 'file-icon inlineb right-space-icon moving-top')%>
            <% end %>
            <% if quotation.quotation_document %>
            <%= link_to quotation.quotation_document.document.url(:original), target: '_blank', class:'inlineb hidden-xs hidden-sm' do %>
            <%= image_tag('file.svg', class: 'file-icon hidden-xs hidden-sm right-space-icon')%>
            <% end %>
            <% end %>
            <a class="collapsed row-toggle-quotation inlineb" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse<%= quotation.id %>" aria-expanded="false" aria-controls="collapse<%= quotation.id %>">
            </a>
          </div>
        </div>
        <% if quotation.customer.try(:core_id).nil? ||  quotation.quotation_products.map{ |qp| qp.product.core_id.nil? || qp.core_id.nil? }.any? %>
          <div>
            <p>
              <%= image_tag('warning.svg', class: 'file-icon inlineb miele-text', style: 'margin: 0 auto !important;') + " Problemas en Core" %>
            </p>
          </div>
        <% end %>
      </div>
      <div id="collapse<%= quotation.id %>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
        <div class="panel-body">
         <div class="row">
          <% if (current_user.administrator? or current_user.manager?) and quotation.partner_commission %>
          <div class="col-md-3 col-xs-6 hidden-md hidden-lg">
           <p><b>Comisión <%= quotation.try(:partner_selected_commission).try(:code) %></b></p>
           <p class="light-quotation"><%= number_to_currency(quotation.try(:partner_commission)) %> <span class="mini-text-gray">(IVA Incluído)</span></p>
         </div>
         <% if quotation.user.is_mca? and show %>
         <div class="col-md-3 col-xs-6 hidden-xs hidden-sm">
           <p><b>Comisión Vendedor</b></p>
           <p class="light-quotation"><%= number_to_currency(quotation.try(:mca_commission)) %> <span class="mini-text-gray">(IVA Incluído)</span></p>
         </div>
         <% end %>
         <% end %>
         <% if quotation.user.is_mca? %>
         <div class="col-md-3 col-xs-6 hidden-md hidden-lg">
           <p><b>Comisión Vendedor</b></p>
           <p class="light-quotation"><%= number_to_currency(quotation.try(:mca_commission)) %> <span class="mini-text-gray">(IVA Incluído)</span></p>
         </div>
         <% end %>
          <div class="col-md-3 col-xs-6 hidden-md hidden-lg">
           <p><b>Correo</b></p>
           <p class="light-quotation"><%= quotation.email %></p>
         </div>
         <div class="col-md-3 col-xs-6 hidden-md hidden-lg">
           <p><b>RUT</b></p>
           <p class="light-quotation"><%= quotation.rut %></p>
         </div>
         <div class="col-md-3 col-xs-6">
           <p><b>Teléfono</b></p>
           <p class="light-quotation"><%= quotation.phone %></p>
         </div>
         <% if quotation.document_type %>
         <div class="col-md-3 col-xs-6">
           <p><b>Tipo de documento</b></p>
           <p class="light-quotation"><%= quotation.document_type %></p>
         </div>
         <% end %>
         <% if quotation.document_type == 'factura' %>
         <div class="col-md-3 col-xs-6">
           <p><b>Razón social</b></p>
           <p class="light-quotation"><%= quotation.try(:business_name) %></p>
         </div>
         <div class="col-md-3 col-xs-6">
           <p><b>RUT Empresa</b></p>
           <p class="light-quotation"><%= quotation.try(:business_rut) %></p>
         </div>
         <% end %>
         <div class="col-md-3 col-xs-6">
           <p><b>Dirección despacho</b></p>
           <p class="light-quotation"><%= quotation.try(:full_dispatch_address) %></p>
         </div>
         <div class="col-md-3 col-xs-6">
           <p><b>Comuna</b></p>
           <p class="light-quotation"><%= quotation.try(:dispatch_commune).try(:name) %></p>
         </div>
         <div class="col-md-3 col-xs-6">
           <p><b>Centro de costo</b></p>
           <p class="light-quotation"><%= quotation.try(:cost_center).try(:code) %></p>
         </div>
         <div class="col-md-3 col-xs-6 hidden-md hidden-lg">
           <p><b>Estado</b></p>
           <p class="light-quotation"><%= get_state_label(quotation.quotation_state, 'mini') %></p>
         </div>
         <div class="col-md-3 col-xs-6 hidden-md hidden-lg">
           <p><b>Descargar</b></p>
           <% if quotation.quotation_document %>
           <%= link_to quotation.quotation_document.document.url(:original), target: '_blank', class:'inlineb' do %>
           <%= image_tag('file.svg', class: 'file-icon')%>
           <% end %>
           <% end %>
         </div>
       </div>
     </div>
   </div>
 </div>

app/views/quotations/_versions_sidebar.html.erb
<div class="versions-alert">
  <p>
    Última modificación el <%= @quotation.created_at.strftime('%d/%m/%Y %H:%M:%S') %>
  </p>
  <%= link_to 'Ver historial de versiones', '#versions-sidebar', id: 'open-sidebar-link' %>
</div>

<div id="versions-sidebar">
  <div class="close-sidebar">
    <%= link_to 'X', '#' %>
  </div>
  <h3>Historial de versiones</h3>

  <% @versions.each do |version| %>
    <%= link_to version do %>
      <div class="version-container <%= 'current-version' if version == @quotation %>">
        <p><%= version.created_at.strftime('%d/%m/%Y %H:%M:%S') %></p>
        <p>
          <%= display_quotation_currency( version.for_project? ? 'uf' : 'clp' ).upcase + ' ' + number_with_delimiter( version.for_project? ? version.total.round(2) : version.total.round(0) ) %>
        </p>
        <p>
          Productos: <%= version.products.count %>
        </p>
        <%= link_to quotation_path(version, format: :pdf), class: 'download-pdf no-loader' do %>
          <%= image_tag 'file.svg' %> Descargar
        <% end %>
        <% if version.valid_quotation %>
          <p class="current-version-label">
            Versión vigente
          </p>
        <% end %>
        <% if version == @quotation %>
          <p class="current-version-label">
            Vista actual
          </p>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>