config/routes.rb
Rails.application.routes.draw do
  resources :detail_quotation_products
  # ROOT PATH
  authenticate :user, lambda { |u| u.administrator? } do
    apipie
  end
  root 'home#index'
  # resources
  devise_for :users, :controllers => {:sessions => 'users/sessions'}
  get '/users/search', to: 'users#search'
  resources :users
  get '/choose_role', to: 'users#choose_role', as: 'choose_role'
  get '/change_role', to: 'users#change_role', as: 'change_role'
  post '/set_role', to: 'users#set_role', as: 'set_role'
  
  resources :promotional_codes
  resources :banners

  # DASHBOARD
  get '/home/filter', to: 'home#filter', as: 'filter_home'
  # BANNERS
  get '/banner/reference', to: 'banners#reference_banner', as: 'reference_banner'
  # PRODUCTOS
  get '/business_units', to: 'products#business_units', as: 'business_units'
  get  '/:business_unit/products', to: 'products#index'     , as: 'products' 
  get  '/search', to: 'products#search', as: 'search_products'
  get  '/product/:sku', to: 'products#show', as: 'product'
  get  '/product/bstock/:sku', to: 'products#show', bstock: true, as: 'bstock_product'
  patch '/product/:id', to: 'products#update', as: 'update_product'
  get '/cart/:id/mandatories_by_instalation/:instalation_id', to: 'cart#mandatories_by_instalation', as: 'mandatories_by_instalation'
  get '/bstocks', to: 'products#bstock', as: 'bstocks'
  post '/product/destroy', to: 'products#destroy', as: 'delete_product'
  patch '/product/:sku/syncronize_with_miele_core', to: 'products#synchronize_one_product_with_miele_core', as: 'synchronize_one_product_with_miele_core'
  
  # COTIZACIONES
  get 'quotations/:id/resumen'     , to: 'quotations#resumen' , as: 'quotation_resumen'
  get '/quotations/search'         , to: 'quotations#search', as: 'search_quotations'
  post '/quotations/:id/check_dispatch/:commune', to: 'quotations#check_dispatch', as: 'check_dispatch'
  post '/quotation/:id/update_payment_info', to: 'quotations#update_payment_info', as: 'update_payment_info'
  get '/quotations/:id/pay_debt', to: 'quotations#pay_debt', as: 'pay_debt'
  post '/quotation/:id/reactivate', to: 'quotations#reactivate', as: 'reactivate_quotation'
  post '/quotation/:id/reactivate_for_project', to: 'quotations#reactivate_for_project', as: 'reactivate_for_project'
  post '/quotation/:id/update_quotation', to: 'quotations#update_quotation', as: 'update_custom_quotation'
  post '/quotation/get_dispatch_cost', to: 'quotations#get_dispatch_cost'
  post '/quotation/get_dispatch_cost_show', to: 'quotations#get_dispatch_cost_show'
  post '/quotation/set_dispatch_value', to: 'quotations#set_dispatch_value'
  post '/quotation/set_installation_value', to: 'quotations#set_installation_value'
  patch '/quotation/:id/update_total_from_view', to: 'quotations#update_total_from_view'


  #normal flow
  post '/quotation/:id/finish', to: 'quotation_flow#cancel_quotation', as: 'cancel_quotation'
  post '/quotation/:id/activate', to: 'quotation_flow#activate', as: 'activate_quotation'
  post '/quotation/:id/dispatch', to: 'quotation_flow#dispatch_activation', as: 'dispatch_quotation'
  post '/quotation/:id/dispatch_confirm', to: 'quotation_flow#dispatch_confirm', as: 'dispatch_confirm_quotation'
  post '/quotation/:id/instalation', to: 'quotation_flow#instalation', as: 'instalation_quotation'
  post '/quotation/:id/activate_home_program', to: 'quotation_flow#activate_home_program', as: 'activate_home_program_quotation'
  post '/quotation/:id/load_billing_documents', to: 'quotation_flow#load_billing_documents', as: 'load_billing_documents'
  #project flow
  post '/quotation/:id/negotiation_quotation', to: 'quotation_flow#negotiation_quotation', as: 'negotiation_quotation'
  post '/quotation/:id/close_quotation', to: 'quotation_flow#close_quotation', as: 'close_quotation'
  post '/quotation/:id/lead_quotation', to: 'quotation_flow#lead_quotation', as: 'lead_quotation'
  #retail flow
  post '/quotation/:id/activate_retail', to: 'quotation_retail#activate_retail', as: 'activate_retail'
  post '/quotation/:id/activate_finance_retail', to: 'quotation_retail#activate_finance_retail', as: 'activate_finance_retail'
  post '/quotation/:id/update_quantities', to: 'quotation_retail#update_quantities', as: 'update_quantities'
  post 'quotations/:id/new_version', to: 'quotations#new_version', as: :new_version
  delete 'quotations/:id', to: 'quotations#destroy', as: :delete_version
  get 'quotations/checkout', to: 'quotations#checkout'
  post 'quotations/checkout_instalation', to: 'quotations#checkout_instalation', as: 'checkout_instalation'
  get 'quotations/:id/send_dispatch_configuration_alert', to: 'quotations#send_dispatch_configuration_alert', as: :send_dispatch_configuration_alert
  patch '/set_instalation_check', to: 'quotations#set_instalation_check'
  get 'quotations/:id/unit_real_states', to: 'quotations#get_unit_real_states'


  resources :quotations, only: [:index, :new, :create, :show, :update, :edit]
  # CARRITO
  get  '/cart', to: 'cart#index', as: 'cart'
  post  '/cart/from_quotation', to: 'cart#from_quotation', as: 'cart_from_quotation'
  post '/cart/add_mandatory_to_cart', to: 'cart#add_mandatory_to_cart', as: 'add_mandatory_to_cart'
  post '/cart/apply_discount', to: 'cart#apply_discount', as: 'apply_discount'
  post 'add_product/:id'           , to: 'cart#add_product'   , as: 'add_product_to_cart'
  post '/add_product_bstock/:id', to: 'cart#add_product_bstock', as: 'add_product_bstock'
  post 'minus_product/:id'         , to: 'cart#minus_product' , as: 'minus_product_to_cart'
  post 'plus_product/:id'          , to: 'cart#plus_product'  , as: 'plus_product_to_cart'
  delete '/cart/empty'               , to: 'cart#empty'         , as: 'empty_cart'
  delete '/remove_product/:id'     , to: 'cart#remove_product', as: 'remove_product'
  post '/change_payment/:percent'  , to: 'cart#change_percent', as: 'change_percent'
  post '/apply_promotion/:type/:id'      , to: 'cart#apply_promotion', as: 'apply_promotion'
  post '/set_dispatch/:id/:value', to: 'cart#set_dispatch', as: 'set_dispatch'
  post '/set_instalation/:id', to: 'cart#set_instalation', as: 'set_instalation'
  get 'cart/update_totals'
  post 'cart/update_item_price'
  post 'cart_items/calculate_margen', to: "cart#calculate_margen"

  #carga de datos
  get '/data_upload'               , to: 'data_upload#upload_info', as: 'upload_info'
  post '/upload/product_photos'    , to: 'data_upload#load_photos', as: 'upload_product_photos'
  post '/upload/mandatory_products', to: 'data_upload#load_mandatory', as: 'upload_mandatory'
  post '/upload/products'          , to: 'data_upload#load_products', as: 'upload_products'
  post '/upload/discounts', to: 'data_upload#load_discounts', as: 'upload_discounts'
  post '/upload/addressees', to: 'data_upload#load_addressees', as: 'upload_addressees'
  post '/upload/stock', to: 'data_upload#load_stock', as: 'upload_stock'
  post '/upload/technical_images', to: 'data_upload#load_technical_images', as: 'upload_technical_images'
  post '/upload/load_comparator_info', to: 'data_upload#load_comparator_info', as: 'load_comparator_info'
  post '/upload/load_homologate_tnr', to: 'data_upload#load_homologate_tnr', as: 'load_homologate_tnr'
  post 'upload/load_oc_retail', to: 'data_upload#load_oc_retail', as: 'load_oc_retail'
  post 'upload/load_quotation_project', to: 'data_upload#load_quotation_project', as: 'load_quotation_project'
  post 'upload/load_cost_center', to: 'data_upload#load_cost_center', as: 'load_cost_center'
  post '/upload/load_miele_roles', to: 'data_upload#load_miele_roles', as: 'load_miele_roles'
  post '/upload/commission_levels', to: 'data_upload#load_commission_levels', as: 'load_commission_levels'
  post '/upload/load_project_installation_value', to: 'data_upload#load_project_installation_value', as: 'load_project_installation_value'
  post '/upload/load_project_installation_discount', to: 'data_upload#load_project_installation_discount', as: 'load_project_installation_discount'
  post '/upload/load_dispatch_rule', to: 'data_upload#load_dispatch_rule', as: 'load_dispatch_rule'
  post '/upload/save_margen', to: 'data_upload#load_save_margen', as: 'load_save_margen'


  patch '/update/customer_core_ids', to: 'data_upload#update_customer_core_ids', as: 'update_customer_core_ids'
  patch '/update/product_core_ids', to: 'data_upload#update_product_core_ids', as: 'update_product_core_ids'
  patch '/update/synchronizeProductsWithMieleCore', to: 'data_upload#synchronizeProductsWithMieleCore', as: 'synchronize_products_with_miele_core'

  get '/download/stock', to: 'data_upload#download_stock', as: 'download_stock'
  get '/download/products_template', to: 'data_upload#download_products', as: 'download_products'
  get '/download/discounts', to: 'data_upload#download_discounts', as: 'download_discounts'
  get '/download/addressees', to: 'data_upload#download_addressees', as: 'download_addressees'
  get '/download/commissions_table', to: 'data_upload#download_commissions_table', as: 'download_commissions_table'
  get '/download/cost_center', to: 'data_upload#download_cost_center', as: 'download_cost_center'
  get '/download/miele_roles', to: 'data_upload#download_miele_roles', as: 'download_miele_roles'
  get '/download/tnr_homologated', to: 'data_upload#download_tnr_homologated', as: 'download_tnr_homologated'
  #usuarios
  get '/upload_users', to: 'users#upload_users', as: 'upload_users'
  post '/load_users', to: 'users#load_users', as: 'load_users'
  post '/users/create_user' => 'users#create_user'
  post '/user/toggle/:id', to: 'users#toggle', as: 'toggle_user'
  get '/download/users', to: 'users#download_users', as: 'download_users'
  #clientes
  get '/customers/search', to: 'customers#search', as: 'search_customer'
  get '/clientes', to: 'customers#search_tracking', as: 'search_tracking'
  get '/busqueda', to: 'customers#find_by_rut_and_code', as: 'find_by_rut_and_code'
  #templates

app/models/product.rb
class Product < ApplicationRecord
  acts_as_paranoid
  scope :outlet_not_bstock, -> {where('(stock > 0 OR stock_break = TRUE) AND outlet = TRUE AND ean IS NULL')}
  scope :not_bstock, -> {where('(stock > 0 OR stock_break = TRUE) AND ean IS NULL')}
  scope :bstock_count, -> {where.not(ean: nil)}
  scope :bstock, -> {where(bstock: true)}
  
  belongs_to :cost_center
  has_and_belongs_to_many :sale_channels, dependent: :destroy
  has_many :instalations, dependent: :destroy

  has_many :cart_items
  has_many :quotation_products
  has_many :quotation_products_auxes
  has_many :images, class_name: 'ProductImage', foreign_key: 'product_id', dependent: :destroy
  has_many :product_families
  has_many :families, through: :product_families

  has_one :product_discount, dependent: :destroy
  has_many :technical_images, dependent: :destroy

  has_many :product_attributes, dependent: :destroy
  has_many :comparable_attributes, through: :product_attributes

  has_many :comparator_products, dependent: :destroy
  has_many :comparators, through: :comparator_products

  has_many :ecommerce_sales, through: :quotation_products

  has_many :retail_products, dependent: :destroy
  has_many :retails, through: :retail_products

  has_many :product_in_dispatch_groups
  has_many :dispatch_groups, through: :product_in_dispatch_groups
  
  def price_formatted
    number_helper.number_with_delimiter(price.round(0))
  end

  def number_helper
    @helper ||= Class.new do
      include ActionView::Helpers::NumberHelper
    end.new
  end

  def display_price(user)
    if (discount_t = self.product_discount) and (discount_t.start_date <= Date.today and discount_t.end_date >= Date.today) and (user.administrator? or user.is_manager_inventory? or discount_t.sale_channels.include?(user.sale_channel))
      return true, (self.price.round(0) - (self.price.round(0) * (discount_t.discount / 100.0))) , discount_t.discount, discount_t.end_date
    else
      return false, self.price.round(0), 0, Date.today
    end
  end

  def get_product_photo(type = nil)
    if self.images.any?
      self.images.first.image.url(:original)
    elsif is_service
      type == 'search' ? ActionController::Base.helpers.asset_path("shopping-cart.svg") : 'shopping-cart.svg'
    else
      type == 'search' ? ActionController::Base.helpers.asset_path("product.png") : 'product.png'
    end 
  end

  def can_supply?
    return (stock > 0 || stock_break)
  end

  def is_service
    self.families.include?(Family.find_by(name: 'Servicios', depth: 0))
  end

  def bstock_price(prod_original)
    (((100 - self.discount.to_i)/100.0) * prod_original.try(:price).to_f)
  end

  def original_product
    Product.find_by(sku: self.sku, ean: nil)
  end

  def check_linked_quotations(quotation_parent = nil)
    self.quotation_products.where("quotation_id is not null AND 
                                   quotation_id != ? AND 
                                   quantity > ? AND 
                                   is_service is false", 
                                   quotation_parent, self.stock)
        .map do |quotation_product| 
      if quotation_product.quotation.get_state == 'Enviada'
        quotation_product.quotation.to_state('Cancelada')
      end
    end
  end

  def self.offer_deadline(ids, sale_channels)
    limit = ProductDiscount.where(product_id: ids)
                           .joins(:sale_channels)
                           .where("product_discounts.end_date BETWEEN ? AND ?", Date.today, (Date.today+30.days))
                           .where(sale_channels: {id: sale_channels})
                           .order(end_date: :asc)
                           .uniq
                           .first
    limit ? [limit.end_date, (limit.end_date - Date.today).to_i] : [(Date.today + 30.days), 30]
  end

  def self.discount_stock(items)
    items.each do |item|
      if !item.product.try(:stock_break)
        item.product.with_lock do
          item.product.stock = (item.product.stock - item.quantity)
          item.product.save
        end
        item.product.check_linked_quotations(item.quotation_id)
      end
    end
  end

  def self.reverse_stock(items)
    items.each do |item|
      if !item.product.try(:stock_break)
        item.product.with_lock do
          item.product.stock = (item.product.stock + item.quantity)
          item.product.save
        end
      end
    end
  end

  def name_and_sku
    return "#{self.sku}-#{self.name}"
  end

  def self.create_to_project_quotations(lead_products)
    products_to_project = lead_products.map do |product| 
      {
        sku: product.sku, 
        name: product.name, 
        price: product.unit_price, 
        only_for_project: true
      }
    end
    Product.create(products_to_project)
  end

	def update_core_id
		response_data = MieleCoreApi.find_product_by_tnr(self.sku)['data']

		if response_data.any?
		  self.update(core_id: response_data.first['id'] )
    end
	end

  def self.bulk_update_core_id
    skus = Product.where(core_id:nil).pluck(:sku).join(",") rescue ""
    puts skus
    response_data = MieleCoreApi.find_product_by_tnr(skus, true)['data'] rescue []
    
    response_data.each do |product|
      p = Product.find_by_sku(product["tnr"])
      p.update(core_id: product['id'] ) if p
    end if response_data.any?
    return true
  end

  # Metodo que actualiza el stock de un producto con miele core antes de mostrarlo
  def fetch_stock_of_product_to_miele_core
    response = MieleCoreApi.fetch_stock([self.sku]) rescue nil
    if response 
      if response["#{self.sku}"]
        self.update!(stock:response["#{self.sku}"])
      else 
        self.update!(stock:0)
      end
    else
      self.update!(stock:0)
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
	def check_offer(product)
		if product.display_price(current_user)[0]
			return '<p class="no-bottom"><span class="new-price">'+number_to_currency(product.display_price(current_user)[1])+'</span></p><p><span class="old-price strikediag">'+number_to_currency(product.price.round(0))+'</span></p>'.html_safe
		else
			return '<p class="product-card-price">'+product.price_formatted+'</p>'.html_safe
		end
	end

	def check_offer_show(product)
		if product.display_price(current_user)[0]
			return '<p><span class="old-price strikediag">'+number_to_currency(product.price)+'</span> <span class="new-price"> '+number_to_currency(product.display_price(current_user)[1])+'</span></p>'.html_safe
		else
			return '<p class="product-price">'+product.price_formatted+'</p>'.html_safe
		end
	end

	def from_price_bstock(product)
		bstock_cheaper = Product.where(sku: product.sku)
													  .where.not(ean: nil)
													  .order('discount DESC')
													  .first
		if bstock_cheaper
			return '<p class="product-card-price">Desde '+number_to_currency(bstock_cheaper.bstock_price(product))+'</p>'
		else
			return '<p class="product-card-price"></p>'
		end
	end

	def any_bstock(product)
		bstock = Product.where(sku: product.sku)
													  .where.not(ean: nil)
													  .order('discount DESC')
		bstock.any?
	end
end

app/views/products/_bstock_details.html.erb
<div class="col-md-5 col-md-offset-1 col-xs-12 col-sm-5">
	<h4 class="title-mobile pt14mobile"><b><%= @product.name %></b></h4>
	<p class="product-sku">TNR <%= @product.sku %></p>
	<% if @bstocks.first %>
		<p class="product-from">
			Desde <%= number_to_currency(@bstocks.first.bstock_price(@product)) %>
		</p>
	<% end %>
	<% if @bstocks.where.not(id: current_user.cart.cart_items.pluck(:product_id)).any? %>
		<% @bstocks.each do |bstock| %>
			<div id="price<%= bstock.id %>" class="striked-price <%= @bstocks.first != bstock ? 'hidden' : '' %>">
				<p class="no-bottom"><span class="new-price"><%= number_to_currency(bstock.bstock_price(@product)) %></span></p>
				<p><span class="old-price strikediag"><%= number_to_currency(@product.price) %></span></p>
			</div>
		<% end %>
	<% end %>
	<% if can? :add_product_bstock, Cart %>
		<% if @bstocks.where.not(id: current_user.cart.cart_items.pluck(:product_id)).any? && any_bstock(@product) %>
			<div class="row full-width" id="form-add-bstock">
				<div class="col-xs-12">
					<%= form_tag add_product_bstock_path(@product), remote: true, class:'inlineb full-width', method: :post do %>
					<%= hidden_field_tag 'quantity', 1 %>
					<div class="width-select-70 inlineb">
						<%= select_tag :bstock_id, options_for_select(@bstocks.where.not(id: current_user.cart.cart_items.pluck(:product_id)).collect{ |bstock| [bstock.category+' - '+bstock.ean+' - '+bstock.discount.to_s+'%', bstock.id] }, 0), { required: true, class:'inlineb width-select-70' } %>
					</div>
					<button type="submit" class="btn btn-miele hidden-xs hidden-sm hidden-md" id="add-to-cart">Cotizar</button>
					<div class="button-submit-bstock hidden-lg">
						<button type="submit" class="btn btn-miele" id="add-to-cart">Cotizar</button>
					</div>
					<% end %>
				</div>
			</div>
		<% end %>
	<% end %>
	<p class="title-description top-both">Descripción</p>
	<% if @bstocks.where.not(id: current_user.cart.cart_items.pluck(:product_id)).size > 0 %>
		<% @bstocks.each do |bstock| %>
			<div id="condition-bstock<%= bstock.id %>" class="miele-text condition-bstock-p <%= @bstocks.first != bstock ? 'hidden' : '' %>">
				<p><%= "Categoría #{bstock.category} - #{bstock.state}" %></p>
				<p><%= "Disponible en #{bstock.cost_center.try(:name)}" %></p>
			</div>
		<% end %>
	<% end %>
	<% if @product.description %>
		<p class="product-description"><%= @product.description %></p>
	<% else %>
		<p class="product-description">Sin descripción disponible</p>
	<% end %>
</div>

<script>
	$("#bstock_id").select2();
	$("#bstock_id").change(function(){
		$(".condition-bstock-p").addClass("hidden");
		$("#condition-bstock"+$(this).val()).removeClass("hidden");
		$(".striked-price").addClass("hidden");
		$("#price"+$(this).val()).removeClass("hidden");
	});
</script>

app/views/products/_details.html.erb
<div class="col-md-5 col-md-offset-1 col-xs-12 col-sm-5">
	<% if current_user.administrator? %>
		<%= form_tag synchronize_one_product_with_miele_core_path(sku:@product.sku), method: :patch do %>
			<button type="submit" class='btn btn-miele-synchronize' >
				Sincronizar Producto con Miele Core
			</button>
		<% end %>
	<% end %>
	<h4 class="title-mobile pt14mobile"><b><%= @product.name %></b></h4> 
	<p class="product-sku">TNR <%= @product.sku %></p>
	<p class="product-sku"><%= @product.stock %> Unidades <%= !@product.stock_break ? '<span class="miele-text">(Descontinuado)</span>'.html_safe : '' %></p>
	<%= check_offer_show(@product).html_safe%>
	<% if can? :add_product, Cart %>
		<% if @product.can_supply? %>
			<div class="row inlineb">
				<%= form_tag add_product_to_cart_path(@product), remote: true, class:'inlineb', method: :post do %>
				<% if @product.is_service %>
				<%= hidden_field_tag 'quantity', 1 %>
				<% else %>
				<div class="text-center cart-stepper-container inlineb left-move-quantity">
					<div class="cart-stepper" onclick="increaseValue()" id="increase">
						<i class="fa fa-angle-up row-angle-after"></i>
					</div>
					<div class="item-quantity">
						<input type="number" name="quantity" id="number" value="1" min="1" class="transparent-back" />
					</div>
					<div class="cart-stepper" onclick="decreaseValue()" id="decrease">
						<i class="fa fa-angle-down row-angle-after"></i>
					</div>
				</div>
				<% end %>
				<div class="<%= !@product.is_service ? 'inlineb align-up' : 'align-service-button' %>">
					<button type="submit" class="btn btn-miele" id="add-to-cart">Cotizar<%= ((@product.stock == 0 && @product.stock_break ) ? " sin Stock" : "")%></button>
					<% if @product.stock <= 2 && @product.stock > 0  %>
						<span class="last-stock hidden-xs hidden-sm left-space"><%= t("last_products_label") %></span>
					<% elsif (@product.stock == 0 && @product.stock_break )  %>
						<span class="last-stock hidden-xs hidden-sm left-space"><%= t("backorderable_label")%></span>
					<% end %>
				</div>
				<% end %>
			</div>
			<% if @product.stock <= 2 && @product.stock > 0  %>
				<p class="last-stock hidden-lg hidden-md"><%= t("last_products_label") %></p>
			<% elsif @product.stock == 0 && @product.stock_break %>
				<p class="last-stock hidden-lg hidden-md"><%= t("backorderable_label")%></p>
			<% end %>	
		<% else %>
			<p class="top-space bot-space">
				<span class="no-stock-card">Sin Stock</span>
			</p>
		<% end %>
	<% end %>
	<p class="title-description">Descripción</p>
	<% if @product.description %>
		<p class="product-description"><%= @product.description %></p>
	<% else %>
		<p class="product-description">Sin descripción disponible</p>
	<% end %>
</div>

app/views/products/_preloader.html.erb
<div class="row">
	<div id="catalog-preloader" class="hidden" align="center">
		<div class="loader-box bottom-space-loader">
			<div class="loader" align="center">
				<svg class="circular" viewBox="25 25 50 50">
					<circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10"/>
				</svg>
			</div>
		</div>
	</div>
</div>

app/views/products/_product.html.erb
<div class="col-sm-6 col-md-4 col-lg-3 col-xs-6 text-center product-item">
	<div class="card">
		<% if product.display_price(current_user)[0] and !product.outlet and (product.ean != nil) %>
			<span class="red-card-name left-card">
				-<%= product.display_price(current_user)[2].try(:round) %>%
			</span>
		<% end %>
		<% if !@bstock and (can? :add_product, Cart) %>
			<div class="card-head">
				<%= link_to '<i class="fas fa-cart-plus"></i>'.html_safe, add_product_to_cart_path(product), class: "product-add-icon transition #{!current_user.foreign? and product.can_supply? ? '' : 'custom-height-whitespace'}", method: :post, remote: true %>
			</div>
		<% end %>

		<%= link_to (@bstock ? bstock_product_path(sku: product.sku) : product_path(sku: product.sku)), class: (@bstock ? (any_bstock(product) ? '' : 'not-available') :(product.can_supply? ? '' : 'not-available')) do %>
			<div class="card-image"><%= image_tag(product.get_product_photo , alt: 'producto', class: 'product-img') %>
			</div>
			<p class="product-card-title"><%= product.name %></p>
			<p class="product-card-title"><b>TNR <%= product.sku %></b></p>
			<% if @bstock %>
				<%= from_price_bstock(product).html_safe %>
			<% else %>
				<%= check_offer(product).html_safe %>
			<% end %>
			<% if !@bstock %>
				<% if !product.can_supply? %>
					<p class="available-soon">Próximamente disponible</p>
				<% elsif product.stock <= 2 && product.stock > 0  %>
					<span class="miele-text pt10-mobile left-space"><%= t("last_products_label") %></span>
				<% elsif product.stock == 0 && product.stock_break %>
					<span class="miele-text pt10-mobile left-space"><%= t("backorderable_label") %></span>
				<% end %>	
			<% else %>
				<% if !any_bstock(product) %>
					<p class="available-soon">Próximamente disponible</p>
				<% end %>	
			<% end %>
		<% end %>
		<% if product.product_attributes.any? and !@bstock %>
			<p class="checkbox checkbox<%= product.id %> fixed-to-bot">
				<label class="product-add-comparator">
					<input type="checkbox" class="check-item" name="comparator<%= product.id %>" id="comparator<%= product.id %>" value="<%= product.id %>" <%= @comparator.products.include?(product) ? 'checked' : ''%>>
					<span class="cr"><i class="cr-icon glyphicon glyphicon-ok"></i></span>
					<span class="hidden-xs">Agregar al comparador </span>
					<span class="hidden-lg hidden-md hidden-sm">Comparar</span>
				</label>
			</p>
		<% end %>
	</div>
</div>

app/views/products/index.js.erb
<% if @products.any? %>
  <% if @destroy %>
    $('#products').html("");
  <% end %>
  <% @products.each do |product| %>
    $('#products').append("<%= j render partial: 'products/product', locals: { product: product } %>");
  <% end %>
<% else %>
  $('#products').html("");
<% end %>

$('#catalog-preloader').addClass("hidden");
<% if @products.next_page %>
  $('#infinite-scrolling').html("");
  $('#infinite-scrolling').append("<%= j will_paginate @products %>");
<% else %>
  $('.pagination').remove();
<% end %>
homologateBoxHeights(".card");

$(".check-item").change(function(){
	if($(this).prop('checked')){
		$.post('/comparator/add/'+$(this).val()+'.js');
	} else{
		$.post('/comparator/remove/'+$(this).val()+'.js');
	}
});